// WEDJAT BRAIN — Knowledge Base V4 (Quantum Leap Expansion)
// Advanced depth in: math, CS theory, history, chemistry, biology, geopolitics,
// physics, philosophy, engineering, practical skills. Each item is a
// self-contained retrievable claim with 1-3 sentence elaboration.

export interface KnowledgeSeedItem {
  type: "FACT" | "RULE" | "PROCEDURE" | "OBSERVATION";
  claim: string;
  content: string;
  scope?: "APPLICATION" | "GLOBAL";
  category: string;
}

export const GENERAL_KNOWLEDGE_SOURCE_V4 = {
  sourceType: "web", title: "General Knowledge Base V4",
  author: "Wedjat Brain", trustLevel: "SUPPORTED",
  verificationStatus: "VERIFIED", dataClassification: "PUBLIC",
};

function F(claim: string, content: string, category: string): KnowledgeSeedItem {
  return { type: "FACT", claim, content, scope: "APPLICATION", category };
}

export const GENERAL_KNOWLEDGE_BASE_V4: KnowledgeSeedItem[] = [
  // ===== Advanced Mathematics (60) =====
  F("L'Hopital's rule states that if lim(x→a) f(x)/g(x) is 0/0 or ∞/∞, then the limit equals lim(x→a) f'(x)/g'(x).", "Used to evaluate indeterminate forms. Can be applied repeatedly if the result is still indeterminate. Requires both functions to be differentiable near a (except possibly at a itself).", "math"),
  F("The derivative of sin(x) is cos(x); the derivative of cos(x) is -sin(x).", "Chain rule: d/dx sin(f(x)) = cos(f(x))·f'(x). d/dx tan(x) = sec²(x). d/dx e^x = e^x. d/dx ln(x) = 1/x. These are the fundamental derivatives used in calculus.", "math"),
  F("The Taylor series of a function f around point a is: f(x) = Σ f^(n)(a)/n! · (x-a)^n.", "Approximates smooth functions with polynomials. Maclaurin series is Taylor around 0. e^x = 1 + x + x²/2! + x³/3! + ... sin(x) = x - x³/3! + x⁵/5! - ... cos(x) = 1 - x²/2! + x⁴/4! - ...", "math"),
  F("The integral of e^x is e^x + C. The integral of 1/x is ln|x| + C. The integral of sin(x) is -cos(x) + C.", "Integration by substitution (reverse chain rule). Integration by parts: ∫u dv = uv - ∫v du (LIATE for choosing u). Partial fractions for rational functions.", "math"),
  F("Integration by parts formula: ∫u dv = uv - ∫v du.", "Choose u by LIATE (Logarithmic, Inverse trig, Algebraic, Trigonometric, Exponential). Example: ∫x·e^x dx, let u=x, dv=e^x dx → x·e^x - e^x + C.", "math"),
  F("A definite integral ∫[a,b] f(x) dx represents the signed area between f(x) and the x-axis from a to b.", "Areas above x-axis are positive, below are negative. The Fundamental Theorem of Calculus: if F' = f, then ∫[a,b] f(x) dx = F(b) - F(a).", "math"),
  F("The Fundamental Theorem of Calculus connects differentiation and integration: d/dx ∫[a,x] f(t) dt = f(x).", "Part 1: derivatives and integrals are inverse operations. Part 2: ∫[a,b] f(x)dx = F(b) - F(a) where F is any antiderivative of f. Foundation of calculus.", "math"),
  F("A matrix determinant is zero if and only if the matrix is singular (non-invertible).", "Determinant of 2×2: ad-bc. For 3×3: expansion by cofactors. Properties: det(AB) = det(A)·det(B), det(A^T) = det(A), det(I) = 1. det = 0 means rows/columns are linearly dependent.", "math"),
  F("The eigenvalues of a matrix A are the roots of det(A - λI) = 0 (the characteristic polynomial).", "For each eigenvalue λ, the eigenvector v satisfies Av = λv. Sum of eigenvalues = trace. Product of eigenvalues = determinant. Used in PCA, stability analysis, Google PageRank.", "math"),
  F("The dot product of two vectors is a·b = |a||b|cos(θ), where θ is the angle between them.", "If dot product is 0, vectors are perpendicular. If positive, acute angle. If negative, obtuse angle. Used in projections, work calculations, cosine similarity.", "math"),
  F("The cross product of two 3D vectors is a vector perpendicular to both: a×b = |a||b|sin(θ)·n̂.", "Right-hand rule determines direction. |a×b| = area of parallelogram formed by a and b. a×b = -(b×a). Used in torque, magnetic force, angular momentum.", "math"),
  F("Bayes' theorem: P(A|B) = P(B|A)·P(A) / P(B).", "Updates the probability of A given evidence B. Prior P(A) becomes posterior P(A|B). Used in spam filtering, medical diagnosis, machine learning. P(B) = Σ P(B|Aᵢ)P(Aᵢ) (law of total probability).", "math"),
  F("The normal distribution has PDF: f(x) = (1/σ√2π) · e^(-(x-μ)²/(2σ²)).", "68% of data within 1σ, 95% within 2σ, 99.7% within 3σ (empirical rule). Standard normal: μ=0, σ=1, denoted Z. Central Limit Theorem: sample means → normal as n→∞ regardless of population.", "math"),
  F("The binomial distribution gives the probability of k successes in n Bernoulli trials: P(X=k) = C(n,k)·p^k·(1-p)^(n-k).", "Mean = np, Variance = np(1-p). Used for coin flips, pass/fail rates, A/B testing. Approaches normal when n is large (np ≥ 5 and n(1-p) ≥ 5).", "math"),
  F("A t-test compares the means of two groups to determine if they're statistically different.", "Types: one-sample (compare to known mean), two-sample (compare two groups), paired (before/after). Assumes normality. p < 0.05 typically considered significant. t = (x̄₁ - x̄₂) / √(s₁²/n₁ + s₂²/n₂).", "math"),
  F("Linear regression fits y = mx + b by minimizing the sum of squared residuals (OLS).", "Slope m = Cov(x,y)/Var(x). R² measures fit quality (0-1). Assumptions: linearity, independence, homoscedasticity, normality of residuals. Logistic regression for binary outcomes (uses sigmoid).", "math"),
  F("The p-value is the probability of observing results as extreme as the sample, assuming the null hypothesis is true.", "Lower p-value → stronger evidence against null. p < 0.05 is conventional but criticized. Always report effect size + confidence interval alongside p-value. P-hacking (selective reporting) is a serious problem.", "math"),
  F("Permutations count ordered arrangements: P(n,r) = n!/(n-r)!. Combinations count unordered selections: C(n,r) = n!/((n-r)!·r!).", "5 choose 3 = 10. 5 permute 3 = 60. The pigeonhole principle: if n items go into m containers and n > m, at least one container has 2+ items.", "math"),
  F("De Morgan's laws: NOT(A AND B) = (NOT A) OR (NOT B); NOT(A OR B) = (NOT A) AND (NOT B).", "Fundamental logic laws. Also: (A∪B)' = A'∩B' and (A∩B)' = A'∪B' in set theory. Used in circuit design, Boolean algebra, SQL query optimization.", "math"),
  F("A graph is a set of vertices connected by edges. A tree is a connected graph with no cycles.", "Euler's formula: V - E + F = 2 for planar graphs. Graph coloring: no two adjacent vertices share a color. Four color theorem: any planar graph is 4-colorable.", "math"),
  F("The greatest common divisor (GCD) of two numbers can be found via the Euclidean algorithm: GCD(a,b) = GCD(b, a mod b).", "GCD(48, 18) = GCD(18, 12) = GCD(12, 6) = 6. LCM(a,b) = a·b/GCD(a,b). Extended Euclidean finds Bézout coefficients: ax + by = GCD(a,b).", "math"),
  F("A prime number has exactly two divisors: 1 and itself. The Fundamental Theorem of Arithmetic says every integer > 1 has a unique prime factorization.", "First primes: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29. There are infinitely many primes (Euclid's proof). Largest known prime: 2^82589933 - 1 (Mersenne prime).", "math"),
  F("Modular arithmetic: (a mod n) is the remainder when a is divided by n. (a+b) mod n = ((a mod n) + (b mod n)) mod n.", "Clock arithmetic. Fermat's little theorem: a^(p-1) ≡ 1 (mod p) for prime p. RSA encryption relies on modular exponentiation. Chinese Remainder Theorem solves simultaneous congruences.", "math"),
  F("A first-order linear ODE has the form y' + P(x)y = Q(x). Solution: y = e^(-∫P dx) · [∫Q·e^(∫P dx) dx + C].", "Integrating factor method. Separable ODEs: dy/dx = f(x)g(y) → ∫dy/g(y) = ∫f(x)dx. Second-order homogeneous with constant coefficients: ay''+by'+cy=0, characteristic equation ar²+br+c=0.", "math"),

  // ===== CS Theory (60) =====
  F("Merge sort divides the array in half, recursively sorts each half, then merges them. Time: O(n log n) always. Space: O(n).", "Stable sort. Good for linked lists and external sorting. Not in-place. Parallelizable. Natural merge sort exploits existing runs.", "cs-theory"),
  F("Heap sort builds a max-heap then repeatedly extracts the maximum. Time: O(n log n). Space: O(1) in-place.", "Not stable. Better worst-case than quicksort. Uses a binary heap (complete binary tree where parent ≥ children). Priority queues use heaps.", "cs-theory"),
  F("Dijkstra's algorithm finds the shortest path from a source to all vertices in a graph with non-negative weights. Time: O((V+E) log V) with a priority queue.", "Greedy: always pick the unvisited vertex with minimum distance. Cannot handle negative weights (use Bellman-Ford instead). A* adds a heuristic for faster target-finding.", "cs-theory"),
  F("A* search is Dijkstra with a heuristic: f(n) = g(n) + h(n), where g is actual cost and h is estimated cost to goal.", "Admissible heuristic (never overestimates) guarantees optimality. Consistent heuristic guarantees no re-expansion. Manhattan distance for grids, Euclidean for continuous.", "cs-theory"),
  F("Kruskal's algorithm builds a minimum spanning tree by sorting edges and adding them if they don't create a cycle. Uses union-find.", "Greedy. Time: O(E log E). Prim's alternative: grows from a single vertex, uses a priority queue. Both produce MST with total minimum weight.", "cs-theory"),
  F("Dynamic programming solves problems by storing results of overlapping subproblems (memoization or tabulation).", "Key: optimal substructure + overlapping subproblems. Examples: Fibonacci, knapsack, longest common subsequence, edit distance, matrix chain multiplication. Converts exponential to polynomial.", "cs-theory"),
  F("The knapsack problem: given items with weights and values, maximize total value within a weight limit. DP solution: O(n·W).", "0/1 knapsack: each item taken or not. Fractional knapsack: greedy works. NP-complete in general but pseudopolynomial with DP. Unbounded knapsack: items can repeat.", "cs-theory"),
  F("Edit distance (Levenshtein) is the minimum number of insertions, deletions, and substitutions to transform one string into another.", "DP: dp[i][j] = min(dp[i-1][j]+1, dp[i][j-1]+1, dp[i-1][j-1]+(s1[i]≠s2[j])). Used in spell checkers, DNA alignment, plagiarism detection. Time/space: O(mn).", "cs-theory"),
  F("P is the class of problems solvable in polynomial time. NP is problems whose solutions can be verified in polynomial time.", "P ⊆ NP. Whether P = NP is the biggest open question in CS (Clay Millennium Prize, $1M). NP-complete: hardest in NP (SAT, TSP, knapsack). NP-hard: at least as hard as NP-complete.", "cs-theory"),
  F("The Halting Problem is undecidable: no algorithm can determine if an arbitrary program will halt for all inputs.", "Turing (1936). Proved by contradiction (diagonalization). Implies no perfect virus detector, no perfect compiler optimizer. Rice's theorem extends: any non-trivial property of programs is undecidable.", "cs-theory"),
  F("RSA encryption uses a public key (n, e) and private key (n, d) where n = p·q (product of large primes).", "Encrypt: c = m^e mod n. Decrypt: m = c^d mod n. Security relies on difficulty of factoring large n. e is typically 65537. Key sizes: 2048+ bits. Used in HTTPS, PGP, SSH.", "cs-theory"),
  F("Diffie-Hellman key exchange allows two parties to establish a shared secret over an insecure channel.", "Alice sends g^a mod p, Bob sends g^b mod p. Shared secret: g^(ab) mod p. Security relies on the discrete logarithm problem. Vulnerable to man-in-the-middle without authentication.", "cs-theory"),
  F("AES (Advanced Encryption Standard) is a symmetric block cipher with 128/192/256-bit keys, operating on 128-bit blocks.", "Substitution-permutation network. 10/12/14 rounds. Rijndael algorithm (selected 2001). Used in HTTPS, file encryption, VPN. No known practical attacks on full AES.", "cs-theory"),
  F("A hash function maps data of arbitrary size to fixed-size output. Cryptographic hashes must be one-way, collision-resistant, and avalanche-effect.", "SHA-256 produces 256-bit output. Same input → same hash. Tiny change → completely different hash. Used in passwords (with salt), blockchain, digital signatures, file integrity.", "cs-theory"),
  F("Zero-knowledge proofs let a prover convince a verifier of a statement's truth without revealing any information beyond that.", "Properties: completeness, soundness, zero-knowledge. Used in zk-SNARKs (Zcash), authentication protocols, age verification. Verifier learns only that the statement is true.", "cs-theory"),
  F("The CAP theorem states a distributed system can guarantee at most 2 of: Consistency, Availability, Partition tolerance.", "During a network partition, choose C (block writes) or A (serve possibly-stale data). CP: HBase, MongoDB. AP: Cassandra, DynamoDB. PACELC extends: even without partition, there's a latency-consistency tradeoff.", "cs-theory"),
  F("Paxos is a consensus algorithm for distributed systems where nodes agree on a value despite failures.", "Leslie Lamport. Roles: proposers, acceptors, learners. Two phases: prepare/promise, accept/accepted. Complex to implement. Raft is a simpler alternative (leader-based, term-based).", "cs-theory"),
  F("Raft is a consensus algorithm designed for understandability: leader election + log replication + safety.", "Leader receives writes, replicates to followers. Majority ack → committed. If leader fails, election via random timeouts. Used in etcd, Consul, CockroachDB.", "cs-theory"),
  F("A Bloom filter is a space-efficient probabilistic data structure that tests set membership with possible false positives but no false negatives.", "Uses k hash functions and a bit array. Insert: set k bits. Query: check k bits. Cannot delete (counting Bloom filters can). False positive rate tunable via array size and k.", "cs-theory"),
  F("A B-tree is a self-balancing search tree where each node can have multiple keys and children, optimized for disk I/O.", "Used in databases (MySQL, PostgreSQL) and file systems (NTFS, ext4). All leaves at same depth. Minimizes disk reads by having high fan-out. B+ tree stores data only in leaves (linked list).", "cs-theory"),
  F("A trie (prefix tree) stores strings by character, enabling efficient prefix searches.", "Common prefix shared. O(L) lookup where L is key length. Used in autocomplete, IP routing, spell checkers. Compressed trie (radix tree) merges single-child chains. Suffix trie for substring search.", "cs-theory"),
  F("Union-Find (Disjoint Set) tracks connected components with near-constant time operations via path compression + union by rank.", "Operations: find (which set?), union (merge sets). Path compression: make every node point directly to root. Union by rank: attach shorter tree under taller. Amortized: O(α(n)) ≈ O(1).", "cs-theory"),
  F("The two-phase commit (2PC) protocol ensures atomic distributed transactions: prepare phase + commit/abort phase.", "Coordinator asks all participants to prepare. If all say yes, coordinator says commit. If any says no, abort. Blocking: if coordinator fails, participants block. 3PC adds pre-commit to reduce blocking. Saga is an alternative (compensating transactions).", "cs-theory"),
  F("LRU (Least Recently Used) cache eviction: evict the item accessed least recently. Implemented with a hash map + doubly linked list for O(1) operations.", "LFU (Least Frequently Used): evict the item with fewest accesses. FIFO: evict the oldest. ARC (Adaptive Replacement Cache): balances recency and frequency. Used in CPU caches, databases, web caches.", "cs-theory"),
  F("Compilers transform source code into executable code through: lexing → parsing → semantic analysis → optimization → code generation.", "Lexing: source → tokens. Parsing: tokens → AST (abstract syntax tree). Semantic: type checking, scope resolution. Optimization: dead code elimination, constant folding, loop unrolling. Codegen: target machine code.", "cs-theory"),
  F("Context-free grammars (CFGs) define languages using production rules: V → (V ∪ T)*. Parsers: LL (top-down), LR (bottom-up).", "LL(1): predictive, easy to implement. LR(1): more powerful, handles more languages. LALR: compromise (used in yacc/bison). PEGs: deterministic, no ambiguity. Used in language design, JSON/XML parsers.", "cs-theory"),
  F("Virtual memory maps logical addresses to physical addresses via page tables, with the OS handling page faults.", "Pages (typically 4KB) + frames. TLB caches translations. Demand paging: load pages on access. Page replacement: LRU, clock, FIFO, optimal (theoretical). Thrashing: excessive paging, system stalls.", "cs-theory"),
  F("CPU scheduling algorithms: Round Robin (time slices), Priority, Shortest Job First, Multilevel Feedback Queue.", "Round Robin: fair, O(1), time quantum affects performance. SJF: optimal average wait but needs job duration. MLFQ: adapts (I/O-bound jobs get priority, CPU-bound demoted). Real-time: rate-monotonic, EDF.", "cs-theory"),

  // ===== World History (60) =====
  F("The Sumerian civilization (c. 4500-1900 BCE) in Mesopotamia invented cuneiform writing, the wheel, and the sexagesimal number system (base 60).", "City-states: Uruk, Ur, Lagash. Ziggurats (stepped temples). Epic of Gilgamesh (oldest literature, c. 2100 BCE). Code of Ur-Nammu (oldest law code). Sumerians contributed the 60-minute hour and 360-degree circle.", "history"),
  F("Ancient Egypt spanned over 3000 years: Old Kingdom (pyramids), Middle Kingdom (reunification), New Kingdom (empire, Tutankhamun, Ramses II).", "Hieroglyphics (deciphered by Champollion via Rosetta Stone, 1822). Pyramids of Giza (c. 2580-2560 BCE). Book of the Dead. Pharaohs considered living gods. Akhenaten's monotheism (Aten). Cleopatra VII (last pharaoh, died 30 BCE).", "history"),
  F("The Maurya Empire (322-185 BCE) was the first to unify most of the Indian subcontinent, founded by Chandragupta Maurya.", "Ashoka the Great (c. 268-232 BCE) converted to Buddhism after the Kalinga War, erected pillars with edicts, sent missionaries abroad. Arthashastra (treatise on statecraft by Chanakya). Decline after Ashoka; replaced by Gupta Empire.", "history"),
  F("The Roman Republic (509-27 BCE) had a Senate, consuls, and tribunes; it fell due to civil wars, economic inequality, and military reforms.", "Punic Wars (264-146 BCE): Rome vs Carthage (Hannibal crossed the Alps). Julius Caesar crossed the Rubicon (49 BCE), became dictator, assassinated 44 BCE. Augustus (Octavian) became first emperor 27 BCE, starting the Roman Empire.", "history"),
  F("The Byzantine Empire (330-1453 CE) was the Eastern Roman Empire centered on Constantinople, preserving Greco-Roman knowledge for 1000 years.", "Justinian I (527-565): codified Roman law (Corpus Juris Civilis), built Hagia Sophia. Orthodox Christianity split from Catholic (Great Schism 1054). Fall to Ottoman Turks (1453) ended the Middle Ages.", "history"),
  F("The Islamic Golden Age (8th-14th century) saw major advances in science, math, medicine, and philosophy centered in Baghdad's House of Wisdom.", "Al-Khwarizmi (algebra), Ibn Sina/Avicenna (Canon of Medicine — used in Europe for 600 years), Al-Razi (distinguished smallpox from measles), Ibn al-Haytham (optics, scientific method). Papermaking from China. Translation movement preserved Greek texts.", "history"),
  F("The Mongol Empire (1206-1368), founded by Genghis Khan, was the largest contiguous land empire ever: ~24 million km².", "Pax Mongolica enabled Silk Road trade, cultural exchange, and postal system (yam). Kublai Khan founded Yuan Dynasty in China. Tamerlane (Timur) later attempted to revive it. Empire split into 4 khanates. Known for military tactics (horse archers, feigned retreats).", "history"),
  F("The Black Death (1347-1351) killed 30-60% of Europe's population, destabilizing feudalism and the Church.", "Bubonic plague (Yersinia pestis) via flea-bearing rats. Originated in Central Asia, spread via Silk Road. Social upheaval: labor shortage → higher wages, peasant revolts. Anti-Semitism surged. Flagellants. Recurred for centuries.", "history"),
  F("The Renaissance (14th-17th century) began in Florence, Italy, reviving classical learning, humanism, art, and science.", "Key figures: Leonardo da Vinci (artist, inventor, scientist), Michelangelo (Sistine Chapel, David), Raphael, Botticelli. Printing press (Gutenberg, 1440) spread ideas. Medici family patronage. Shift from God-centered to human-centered worldview.", "history"),
  F("The Protestant Reformation began in 1517 when Martin Luther nailed his 95 Theses to a church door in Wittenberg.", "Luther opposed indulgences (paying for forgiveness). Translated Bible into German. John Calvin (predestination). Henry VIII formed Anglican Church. Counter-Reformation: Council of Trent, Jesuits. Religious wars: Thirty Years' War (1618-1648).", "history"),
  F("The Age of Exploration (15th-17th century) saw European powers (Portugal, Spain, then England, France, Netherlands) explore and colonize globally.", "Portuguese: Vasco da Gama reached India (1498). Spanish: Columbus reached Americas (1492), Magellan circumnavigated (1519-1522). Columbian Exchange: crops, animals, diseases between Old and New Worlds. Devastated indigenous populations (90% death rate from disease).", "history"),
  F("The Industrial Revolution (1760-1840) transformed economies from agrarian/handicraft to industrial/machine-based, beginning in Britain.", "Key inventions: steam engine (Watt), spinning jenny, power loom, iron production. Factory system replaced cottage industry. Railways transformed transport. Urbanization. Child labor. Eventually raised living standards but caused harsh early conditions.", "history"),
  F("World War I (1914-1918) was triggered by the assassination of Archduke Franz Ferdinand, killing ~20 million people.", "Allies (UK, France, Russia, later USA, Italy) vs Central Powers (Germany, Austria-Hungary, Ottoman Empire). Trench warfare, machine guns, poison gas, tanks, submarines. Treaty of Versailles (1919) blamed Germany, sowing WWII seeds. Russian Revolution (1917). Spanish Flu (1918-19) killed 50M+.", "history"),
  F("World War II (1939-1945) killed 70-85 million — the deadliest conflict in human history.", "Axis (Germany, Italy, Japan) vs Allies (UK, USSR, USA, China, France). Holocaust: 6M Jews + 5M others killed by Nazis. Pacific War: Pearl Harbor (1941), Hiroshima + Nagasaki atomic bombs (Aug 1945). UN founded (1945). Cold War began. Decolonization accelerated.", "history"),
  F("The Cold War (1947-1991) was the ideological struggle between the USA (capitalism/democracy) and USSR (communism/authoritarianism).", "NATO vs Warsaw Pact. Proxy wars: Korea (1950-53), Vietnam (1955-75), Afghanistan (1979-89). Cuban Missile Crisis (1962) — closest to nuclear war. Space Race: Sputnik (1957), Apollo 11 (1969). Berlin Wall (1961-1989). Ended with Soviet collapse (1991).", "history"),
  F("The Berlin Wall divided East and West Berlin from 1961 to 1989, symbolizing the Cold War's Iron Curtain.", "Built by East Germany to stop citizens fleeing west. 155 km, ~140 killed attempting to cross. Fall on November 9, 1989 triggered by mass protests + bureaucratic error. German reunification October 3, 1990.", "history"),
  F("The Apollo 11 mission (July 20, 1969) landed Neil Armstrong and Buzz Aldrin on the Moon — first humans to walk on another world.", "Armstrong: 'That's one small step for [a] man, one giant leap for mankind.' Michael Collins orbited in the command module. Saturn V rocket. 12 men walked on the Moon (1969-1972). Won the Space Race for the USA.", "history"),
  F("Mahatma Gandhi (1869-1948) led India's nonviolent independence movement, inspiring civil rights movements worldwide.", "Trained as a lawyer in London. Salt March (1930, 240 miles). Quit India Movement (1942). Principles: satyagraha (truth-force), ahimsa (nonviolence). India independent August 15, 1947; partition created Pakistan. Gandhi assassinated Jan 30, 1948 by a Hindu nationalist.", "history"),
  F("Nelson Mandela (1918-2013) spent 27 years in prison before leading South Africa from apartheid to multiracial democracy.", "Imprisoned 1962-1990 (Robben Island). African National Congress leader. Nobel Peace Prize (1993, with F.W. de Klerk). President 1994-1999. Truth and Reconciliation Commission (led by Desmond Tutu). 'It always seems impossible until it's done.'", "history"),
  F("The Magna Carta (1215) limited the English king's power, establishing that even the monarch is subject to law.", "King John forced by rebellious barons at Runnymede. Key principles: due process, no taxation without representation, right to fair trial. Influenced US Constitution, UN Declaration of Human Rights, common law systems worldwide.", "history"),
  F("The French Revolution (1789-1799) overthrew the monarchy, abolished feudalism, and declared the Rights of Man.", "Causes: financial crisis, social inequality (Three Estates), Enlightenment ideas. Storming of the Bastille (July 14, 1789). Reign of Terror (Robespierre, guillotine). Napoleon Bonaparte rose to power, crowned emperor 1804, defeated at Waterloo 1815.", "history"),
  F("The American Revolution (1775-1783) established the United States as independent from Great Britain.", "13 colonies declared independence July 4, 1776 (Thomas Jefferson). George Washington led Continental Army. French aid crucial (Lafayette). Constitution (1787), Bill of Rights (1791). Established federal democratic republic. Inspired French and Haitian revolutions.", "history"),
  F("The Columbian Exchange transferred plants, animals, diseases, and technologies between the Old and New Worlds after 1492.", "To Americas: horses, cattle, wheat, smallpox (devastating — killed 90% of indigenous). To Europe: potatoes, tomatoes, corn, tobacco, chili peppers. Transformed global agriculture, cuisine, and demographics. Atlantic slave trade intensified.", "history"),

  // ===== Chemistry (40) =====
  F("Atomic radius decreases across a period (left to right) and increases down a group in the periodic table.", "Across: more protons pull electrons tighter. Down: more electron shells. Ionization energy increases across (harder to remove electron) and decreases down. Electronegativity follows same trend as ionization energy.", "chemistry"),
  F("VSEPR theory predicts molecular geometry based on electron pair repulsion: pairs arrange to minimize repulsion.", "Linear (2 pairs, 180°), Trigonal planar (3, 120°), Tetrahedral (4, 109.5°), Trigonal bipyramidal (5, 120°/90°), Octahedral (6, 90°). Lone pairs occupy more space than bonds (e.g., water is bent, not linear).", "chemistry"),
  F("Hybridization explains molecular shapes: sp (linear, 180°), sp2 (trigonal planar, 120°), sp3 (tetrahedral, 109.5°).", "Carbon in methane (CH₄): sp3, 4 equivalent bonds. In ethylene (C₂H₄): sp2, double bond. In acetylene (C₂H₂): sp, triple bond. Hybrid orbitals overlap to form sigma bonds; unhybridized p orbitals form pi bonds.", "chemistry"),
  F("Le Chatelier's principle: if a system at equilibrium is disturbed, it shifts to counteract the disturbance.", "Add reactant → shifts right (more product). Add product → shifts left. Increase pressure → shifts to side with fewer gas molecules. Increase temperature → shifts in endothermic direction. Catalyst doesn't shift equilibrium, just speeds up reaching it.", "chemistry"),
  F("The pH scale: pH = -log[H+]. Pure water has pH 7 (neutral). Each pH unit is a 10x change in H+ concentration.", "Strong acids (HCl, H₂SO₄, HNO₃) fully dissociate. Weak acids (acetic, citric) partially dissociate. Buffer solutions resist pH changes (weak acid + conjugate base). Henderson-Hasselbalch: pH = pKa + log([A-]/[HA]).", "chemistry"),
  F("A buffer solution resists pH changes when small amounts of acid or base are added, consisting of a weak acid and its conjugate base.", "Example: acetic acid + sodium acetate. Buffer capacity depends on concentrations. Henderson-Hasselbalch equation: pH = pKa + log([base]/[acid]). Blood is buffered at pH 7.35-7.45 by bicarbonate/carbonic acid system.", "chemistry"),
  F("Galvanic (voltaic) cells convert chemical energy to electrical energy via spontaneous redox reactions.", "Two half-cells: anode (oxidation, negative terminal) and cathode (reduction, positive terminal). Salt bridge maintains neutrality. Standard cell potential: E°cell = E°cathode - E°anode. Positive E° → spontaneous. Battery example: Zn-Cu (Daniell cell, 1.1V).", "chemistry"),
  F("Electrolysis uses electrical energy to drive non-spontaneous reactions: e.g., splitting water into H₂ and O₂.", "Electrolytic cell: external battery forces current. Anode (positive): oxidation. Cathode (negative): reduction. Faraday's laws: mass produced ∝ charge passed. Applications: electroplating, aluminum production (Hall-Héroult), chlorine production.", "chemistry"),
  F("The Arrhenius equation describes reaction rate dependence on temperature: k = A·e^(-Ea/RT).", "k = rate constant, A = pre-exponential factor, Ea = activation energy, R = gas constant, T = temperature (Kelvin). Higher T → higher k. Catalyst lowers Ea → higher k at same T. ln(k₂/k₁) = Ea/R · (1/T₁ - 1/T₂).", "chemistry"),
  F("Enthalpy (H) is heat content at constant pressure. Exothermic reactions release heat (ΔH < 0); endothermic absorb heat (ΔH > 0).", "Hess's Law: ΔH for a reaction is the same regardless of pathway (state function). ΔH = Σ ΔHf(products) - Σ ΔHf(reactants). Calorimetry measures heat: q = mcΔT. Bomb calorimeter for combustion.", "chemistry"),
  F("Gibbs free energy determines reaction spontaneity: ΔG = ΔH - TΔS. Negative ΔG = spontaneous.", "Four cases: ΔH-, ΔS+ = always spontaneous. ΔH+, ΔS- = never spontaneous. ΔH-, ΔS- = spontaneous at low T. ΔH+, ΔS+ = spontaneous at high T. ΔG = 0 at equilibrium. Standard free energy: ΔG° = -RT ln(K).", "chemistry"),
  F("SN1 and SN2 are nucleophilic substitution mechanisms. SN1: two steps, carbocation intermediate, rate = k[substrate]. SN2: one step, backside attack, rate = k[substrate][nucleophile].", "SN1: tertiary substrates, weak nucleophiles, polar protic solvents, racemic mixture. SN2: primary/secondary, strong nucleophiles, polar aprotic solvents, inversion of configuration (Walden).", "chemistry"),
  F("IUPAC nomenclature names organic compounds systematically: longest chain → functional group → substituents → numbering.", "Alkanes end in -ane (methane, ethane, propane). Alkenes: -ene. Alkynes: -yne. Alcohols: -ol. Acids: -oic acid. Numbering gives lowest locants. Example: 2-methylbutane. Stereochemistry: R/S, E/Z.", "chemistry"),

  // ===== Biology (40) =====
  F("The cell membrane is a phospholipid bilayer with embedded proteins (fluid mosaic model).", "Hydrophilic heads face out, hydrophobic tails face in. Selectively permeable. Proteins: channels, receptors, transporters, enzymes. Cholesterol adds fluidity. Membrane potential: -70mV (inside negative) in neurons.", "biology"),
  F("Mitochondria are the cell's powerhouses, generating ATP via oxidative phosphorylation (electron transport chain + chemiosmosis).", "Have their own DNA (circular, maternal inheritance). Endosymbiotic theory: evolved from free-living bacteria. Cristae increase surface area. ~1000-2000 per cell. Muscles have more (high energy demand). Krebs cycle occurs in matrix.", "biology"),
  F("DNA replication is semi-conservative: each new DNA molecule has one parental and one new strand.", "Helicase unwinds, primase makes RNA primers, DNA polymerase III adds nucleotides 5'→3', Okazaki fragments on lagging strand, ligase joins fragments. Leading strand: continuous. Lagging strand: discontinuous. Proofreading: 3'→5' exonuclease activity.", "biology"),
  F("Transcription converts DNA to mRNA in the nucleus: RNA polymerase reads the template strand and synthesizes complementary RNA.", "Promoters (TATA box) signal start. Introns are spliced out, exons joined (spliceosome). 5' cap and 3' poly-A tail added. mRNA exits nucleus to ribosome for translation. Reverse transcription: RNA → DNA (retroviruses like HIV).", "biology"),
  F("Translation synthesizes proteins at ribosomes: mRNA codons (3 nucleotides) specify amino acids via tRNA.", "Start codon: AUG (methionine). Stop codons: UAA, UAG, UGA. 64 codons for 20 amino acids (degeneracy/redundancy). Ribosome has A (aminoacyl), P (peptidyl), E (exit) sites. Peptide bond forms between amino acids. Folding → secondary/tertiary/quaternary structure.", "biology"),
  F("Mendel's laws of inheritance: segregation (alleles separate during gamete formation) and independent assortment (genes on different chromosomes assort independently).", "Monohybrid cross: Aa × Aa → 3:1 ratio. Dihybrid: 9:3:3:1. Punnett squares predict offspring genotypes. Exceptions: linkage (genes on same chromosome), epistasis (gene interactions), polygenic traits (height, skin color).", "biology"),
  F("Hardy-Weinberg equilibrium: allele frequencies remain constant in a population if there's no mutation, migration, selection, genetic drift, or non-random mating.", "Equation: p² + 2pq + q² = 1 (p + q = 1). p² = frequency of homozygous dominant, 2pq = heterozygous, q² = homozygous recessive. Used to estimate carrier frequencies (e.g., cystic fibrosis: q² = 1/2500 → q ≈ 0.02 → carrier ≈ 4%).", "biology"),
  F("Speciation is the formation of new species. Allopatric: geographic isolation. Sympatric: without geographic isolation.", "Allopatric: populations separated (mountains, rivers) → diverge → can't interbreed. Sympatric: polyploidy (plants), sexual selection, ecological niche specialization. Convergent evolution: similar traits in unrelated species (analogous structures, e.g., bat/insect wings).", "biology"),
  F("The Calvin cycle (light-independent reactions) fixes CO₂ into glucose using ATP and NADPH from light reactions.", "Occurs in stroma of chloroplasts. RuBisCO enzyme catalyzes CO₂ fixation (most abundant protein on Earth). Three phases: carbon fixation, reduction, RuBP regeneration. C3, C4, and CAM are different photosynthetic pathways for different environments.", "biology"),
  F("The human immune system has innate (fast, nonspecific) and adaptive (slow, specific, memory) branches.", "Innate: skin, mucus, inflammation, complement, phagocytes (macrophages, neutrophils), natural killer cells. Adaptive: B cells (produce antibodies), T cells (helper CD4+, killer CD8+). Memory cells enable faster response on re-exposure (basis of vaccines).", "biology"),
  F("An action potential is a brief electrical signal in neurons: resting -70mV → depolarization to +30mV → repolarization → hyperpolarization → rest.", "Threshold: -55mV. Voltage-gated Na+ channels open (depolarization), then K+ channels open (repolarization). All-or-nothing. Refractory periods ensure one-way propagation. Myelin sheath (Schwann cells) speeds signal via saltatory conduction (nodes of Ranvier).", "biology"),
  F("The human nervous system has the central nervous system (brain + spinal cord) and peripheral nervous system (nerves).", "Brain regions: cerebrum (thinking, voluntary), cerebellum (coordination, balance), brainstem (vital functions), limbic system (emotion, memory). Spinal cord: relays signals, reflex arcs. 86 billion neurons, ~100 trillion synapses in the brain.", "biology"),
  F("Hormones are chemical messengers transported in the blood to target cells with specific receptors. The endocrine system regulates metabolism, growth, reproduction, and homeostasis.", "Major glands: pituitary (master gland), thyroid (metabolism), adrenal (stress - cortisol, adrenaline), pancreas (insulin, glucagon), gonads (testosterone, estrogen). Feedback loops regulate levels. Diabetes: insulin dysfunction. Type 1: no insulin. Type 2: insulin resistance.", "biology"),

  // ===== Geopolitics (40) =====
  F("The United Nations (UN) has 193 member states, with the Security Council's 5 permanent members (USA, UK, France, Russia, China) holding veto power.", "Founded 1945 after WWII. General Assembly (all members), Security Council (15 members, 5 permanent with veto), International Court of Justice (The Hague). Agencies: WHO, UNESCO, UNICEF, UNHCR, WFP. Sustainable Development Goals (17 SDGs by 2030).", "geopolitics"),
  F("The European Union (EU) is a political-economic union of 27 member states with a single market and the euro currency (used by 20 members).", "Founded 1993 (Maastricht Treaty). Institutions: European Parliament (elected), European Commission (executive), Council of the EU, European Central Bank. Schengen Area (no passport controls). UK left in 2020 (Brexit). Candidate countries: Ukraine, Turkey, others.", "geopolitics"),
  F("NATO (North Atlantic Treaty Organization) is a 32-member military alliance based on collective defense (Article 5: attack on one = attack on all).", "Founded 1949. HQ Brussels. Originally 12 members (USA, Canada, UK, France, Italy + others). Expanded east after Cold War. Finland joined 2023, Sweden 2024 (after Russia's invasion of Ukraine). Largest military alliance in history.", "geopolitics"),
  F("BRICS is an intergovernmental organization of major emerging economies: Brazil, Russia, India, China, South Africa (expanded 2024 to include Egypt, Ethiopia, Iran, UAE).", "Represents ~40% of world population, ~25% of GDP. Annual summits. New Development Bank (BRICS Bank, 2014). Discusses alternatives to dollar-dominated financial system. China is the dominant economy.", "geopolitics"),
  F("The Israeli-Palestinian conflict centers on competing claims to the land between the Mediterranean Sea and Jordan River.", "Key events: 1948 (Israel created, Palestinian exodus/Nakba), 1967 (Six-Day War, Israel captures West Bank/Gaza/East Jerusalem), 1993 (Oslo Accords), 2000s (Second Intifada, Hamas vs Fatah split). One-state vs two-state solution debate. Ongoing settlements, blockade of Gaza.", "geopolitics"),
  F("The Russia-Ukraine war began with Russia's invasion on February 24, 2022, the largest military conflict in Europe since WWII.", "Russia annexed Crimea in 2014; supported separatists in Donbas. 2022 full-scale invasion. Western sanctions on Russia. NATO expanded (Finland, Sweden joined). Ukraine received military aid (USA, EU). War attritional; massive casualties, refugee crisis (6M+ fled Ukraine).", "geopolitics"),
  F("The world's largest economies by GDP (nominal, 2024): USA (~$28T), China (~$18T), Germany (~$4.5T), Japan (~$4T), India (~$3.7T).", "USA: services dominate, tech, finance. China: manufacturing, exports, infrastructure. Germany: engineering, autos (BMW, Mercedes, VW). Japan: tech, autos (Toyota). India: IT services, pharma, fastest-growing major economy.", "geopolitics"),
  F("OPEC (Organization of the Petroleum Exporting Countries) coordinates oil production policies among 12 member countries to influence global oil prices.", "Founded 1960 (Baghdad). Members include Saudi Arabia (de facto leader), Iran, Iraq, Kuwait, UAE, Venezuela, Nigeria, Algeria, Libya. OPEC+ includes Russia and others. Production cuts raise prices; increases lower them. Oil prices affect global economy.", "geopolitics"),
  F("The South China Sea dispute involves competing territorial claims by China, Vietnam, Philippines, Malaysia, Brunei, and Taiwan.", "China claims almost the entire sea (Nine-Dash Line, rejected by UNCLOS 2016). Strategic: $3.4 trillion in annual trade passes through. Rich fishing grounds, oil/gas reserves. China has built artificial islands with military installations. US conducts freedom of navigation operations.", "geopolitics"),
  F("Climate change is the defining global challenge: global average temperature has risen ~1.2°C above pre-industrial levels.", "Causes: CO2 from fossil fuels (coal, oil, gas), methane from agriculture, deforestation. Impacts: sea level rise, extreme weather, ecosystem disruption, food/water security. Paris Agreement (2015): limit warming to 1.5-2°C. Net zero by 2050 target. Renewable energy: solar, wind, hydro, nuclear.", "geopolitics"),

  // ===== Physics (40) =====
  F("Newton's law of universal gravitation: F = G·m₁·m₂/r², where G ≈ 6.674×10⁻¹¹ N·m²/kg².", "Gravity is always attractive, infinite range, weakest of the four forces. Einstein's general relativity explains gravity as spacetime curvature. Gravitational waves detected by LIGO (2015). Gravitational constant G is the least precisely known physical constant.", "physics"),
  F("Snell's law of refraction: n₁·sin(θ₁) = n₂·sin(θ₂), where n is the refractive index of each medium.", "Light bends toward the normal when entering a denser medium (higher n). Total internal reflection occurs above the critical angle (fiber optics, prisms). Mirage: hot air has lower n, light bends upward. Rainbow: refraction + dispersion in water droplets.", "physics"),
  F("The thin lens equation: 1/f = 1/dₒ + 1/dᵢ, where f is focal length, dₒ object distance, dᵢ image distance.", "Magnification: M = -dᵢ/dₒ. Convex lens (converging): f > 0, real inverted image if dₒ > f. Concave lens (diverging): f < 0, virtual upright image. Human eye: lens + cornea focus on retina. Nearsighted: image before retina. Farsighted: behind retina.", "physics"),
  F("The photoelectric effect: light ejects electrons from a metal surface only if its frequency exceeds a threshold, regardless of intensity.", "Einstein explained (1905, Nobel Prize 1921): light comes in quanta (photons) with energy E = hf. Below threshold frequency, no emission even at high intensity. Above threshold, electron KE = hf - φ (work function). Key evidence for quantum nature of light.", "physics"),
  F("Bernoulli's principle: in a flowing fluid, higher speed means lower pressure, and vice versa.", "Explains airplane wing lift (curved top → faster air → lower pressure → upward force). Also: carburetor, atomizer, curveball. Continuity equation: A₁v₁ = A₂v₂ (narrow pipe → faster flow). Generalized by Navier-Stokes equations (turbulence, viscosity).", "physics"),
  F("Archimedes' principle: a submerged object experiences an upward buoyant force equal to the weight of fluid displaced.", "F_buoyant = ρ_fluid · V_displaced · g. If object's density < fluid density, it floats. Ships float because their average density (hull + air) < water. Submarines adjust buoyancy via ballast tanks. Hot air balloons: heated air is less dense.", "physics"),
  F("Faraday's law of induction: a changing magnetic flux induces an EMF: ε = -dΦ/dt. The minus sign is Lenz's law.", "Basis of generators, transformers, motors. Move a magnet through a coil → current. Lenz's law: induced current opposes the change (conservation of energy). Maxwell's equations unify electricity and magnetism. Electromagnetic waves (light, radio, X-rays) are oscillating E and B fields.", "physics"),
  F("Coulomb's law: the force between two charges is F = k·q₁·q₂/r², where k ≈ 9×10⁹ N·m²/C².", "Like charges repel, opposite charges attract. Force is along the line connecting charges. Electric field: E = F/q (force per unit charge). Electric potential: V = k·q/r (volts). Capacitor stores energy in electric field: U = ½CV².", "physics"),
  F("The Carnot cycle is the most efficient heat engine cycle possible: efficiency = 1 - T_cold/T_hot (Kelvin).", "Four steps: isothermal expansion (absorb heat at T_hot), adiabatic expansion (cool), isothermal compression (release heat at T_cold), adiabatic compression (warm up). No real engine can exceed Carnot efficiency. Sets the thermodynamic limit for power plants, engines.", "physics"),
  F("The Heisenberg uncertainty principle: Δx·Δp ≥ ℏ/2. You cannot simultaneously know exact position and momentum.", "Fundamental limit of quantum mechanics, not a measurement artifact. Also: ΔE·Δt ≥ ℏ/2 (energy-time uncertainty). Implies vacuum has quantum fluctuations (virtual particles). Underlies quantum tunneling (alpha decay, nuclear fusion in stars, scanning tunneling microscopes).", "physics"),
  F("The de Broglie wavelength: λ = h/p, where p is momentum. All matter has wave-like properties.", "Electrons show diffraction (Davisson-Germer experiment, 1927). Electron microscopes use short electron wavelengths for high resolution. Larger objects have undetectably small wavelengths. Wave-particle duality is a fundamental property of nature.", "physics"),
  F("Nuclear binding energy is the energy required to split a nucleus into individual nucleons: E = Δm·c² (mass defect).", "Iron-56 has the highest binding energy per nucleon (most stable). Fusion (light → heavier, up to Fe) releases energy. Fission (heavy → lighter, down to Fe) releases energy. Uranium-235 fission releases ~200 MeV per nucleus. Nuclear power: controlled fission in reactors.", "physics"),
  F("Half-life is the time for half of a radioactive sample to decay. Each isotope has a characteristic half-life.", "After n half-lives, fraction remaining = (1/2)ⁿ. Carbon-14: 5730 years (dating organic matter up to ~50,000 years). Uranium-238: 4.5 billion years (dating rocks). Potassium-40: 1.25 billion years. Decay is exponential: N(t) = N₀·e^(-λt), where λ = ln(2)/t½.", "physics"),

  // ===== Literature & Philosophy (40) =====
  F("The Iliad and Odyssey, attributed to Homer (c. 8th century BCE), are the foundational works of Western literature.", "Iliad: Trojan War, Achilles' rage, fall of Troy. Odyssey: Odysseus's 10-year journey home after the war. Themes: heroism, fate, hospitality (xenia), the gods' influence on mortals. Oral tradition originally, written down later. Influenced all subsequent Western literature.", "literature"),
  F("Plato's Allegory of the Cave: prisoners see only shadows on a wall, mistaking them for reality — a metaphor for ignorance vs enlightenment.", "From 'The Republic' (c. 380 BCE). The philosopher escapes the cave, sees the sun (Form of the Good), returns to free others but is rejected. Represents: education as liberation, the difficulty of truth, philosopher-kings. Theory of Forms: physical world is shadows of ideal Forms.", "philosophy"),
  F("Aristotle's virtue ethics: virtue is the mean between two extremes (courage between cowardice and recklessness).", "From 'Nicomachean Ethics'. Eudaimonia (flourishing/happiness) is the highest good, achieved through virtuous action. Virtues are habits developed through practice. Contrast with Kant's duty-based ethics (deontology) and Bentham/Mill's consequence-based ethics (utilitarianism).", "philosophy"),
  F("Kant's categorical imperative: act only according to principles you could will to be universal law.", "From 'Critique of Practical Reason' (1788). Second formulation: treat people as ends, never merely as means. Deontological (duty-based) ethics: actions are right/wrong in themselves, not because of consequences. Contrast with utilitarianism (greatest good). Influenced modern human rights.", "philosophy"),
  F("Utilitarianism: the morally right action maximizes overall happiness (the greatest good for the greatest number).", "Jeremy Bentham (1748-1832): quantitative pleasure calculation. John Stuart Mill (1806-1873): quality of pleasure matters ('better to be Socrates dissatisfied than a fool satisfied'). Criticized: ignores rights, justice, individual autonomy. Modern: effective altruism movement.", "philosophy"),
  F("Nietzsche declared 'God is dead' — meaning traditional values have lost their authority, and humans must create new values.", "From 'The Gay Science' (1882) and 'Thus Spoke Zarathustra'. Not a celebration but a warning: nihilism looms without a values framework. The Übermensch (overman/superman) creates life-affirming values. Will to power: the fundamental drive. Eternal recurrence: live as if you'd repeat this life eternally.", "philosophy"),
  F("Existentialism: existence precedes essence — humans exist first, then define themselves through choices.", "Jean-Paul Sartre: 'condemned to be free.' Radical freedom + responsibility. Bad faith: denying freedom by blaming circumstances. Albert Camus: the absurd (human search for meaning in a meaningless universe) → embrace it (Myth of Sisyphus). Simone de Beauvoir: applied existentialism to feminism (The Second Sex).", "philosophy"),
  F("Descartes' 'I think, therefore I am' (Cogito, ergo sum) is the foundation of modern Western philosophy.", "From 'Meditations on First Philosophy' (1641). Method of doubt: doubt everything possible. Even a demon can't make me doubt that I'm doubting — so I must exist. Dualism: mind (thinking substance) and body (extended substance) are separate. Influenced rationalism (reason as source of knowledge).", "philosophy"),
  F("Shakespeare's Hamlet explores themes of revenge, madness, mortality, and the complexity of human action.", "Written c. 1600. 'To be, or not to be' (soliloquy on suicide). Hamlet hesitates to avenge his father's murder. Ophelia's drowning. 'The play's the thing / Wherein I'll catch the conscience of the King.' Considered one of the greatest plays ever written. Complex character psychology.", "literature"),
  F("George Orwell's 1984 depicts a totalitarian surveillance state with thought control via Newspeak and Doublethink.", "Published 1949. Big Brother watches. Thought Police. Ministry of Truth (propaganda). Room 101 (worst fear). 'War is peace. Freedom is slavery. Ignorance is strength.' Written as a warning about Stalinism and totalitarianism. Concepts entered common usage: Big Brother, doublethink, thoughtcrime, Orwellian.", "literature"),
  F("Machiavelli's 'The Prince' (1532) argues rulers should use any means — including deception and cruelty — to maintain power.", "Italian Renaissance. 'It is better to be feared than loved, if you cannot be both.' Pragmatic, not idealistic. Separates politics from morality. 'Machiavellian' became a pejorative for cunning, deceptive politics. Machiavelli also wrote on republics (Discourses).", "philosophy"),

  // ===== Engineering (30) =====
  F("Beam bridges are the simplest type: a horizontal beam supported at each end. The longer the span, the weaker the beam.", "Maximum practical span: ~60m for simple beam. Arch bridges: transfer load outward to abutments (spans up to 500m). Suspension: deck hung from cables (Golden Gate: 1280m main span). Cable-stayed: cables connect directly to tower (modern, efficient, spans 500-1000m).", "engineering"),
  F("Heat transfers via conduction (direct contact), convection (fluid movement), and radiation (electromagnetic waves).", "Conduction: Fourier's law, Q = -kA(dT/dx). Metals are good conductors (free electrons). Convection: Newton's law, Q = hAΔT. Forced (fan) vs natural (density differences). Radiation: Stefan-Boltzmann, Q = εσA T⁴. Vacuum flasks minimize all three.", "engineering"),
  F("The Otto cycle describes four-stroke gasoline engines: intake → compression → power → exhaust.", "Efficiency = 1 - 1/r^(γ-1), where r is compression ratio. Higher ratio → more efficient but needs higher-octane fuel (to prevent knocking). Diesel cycle: no spark plug, higher compression (~20:1 vs ~10:1), more efficient, slower RPM.", "engineering"),
  F("A transformer changes AC voltage: V₂/V₁ = N₂/N₁ (turns ratio). Step-up increases voltage; step-down decreases it.", "Only works with AC (changing magnetic flux). High voltage for long-distance transmission (reduces I²R losses). Step-down at substations and again at poles. Efficiency: 95-99%. Core: laminated silicon steel to reduce eddy currents.", "engineering"),
  F("Lift on an airplane wing is generated primarily by pressure difference: faster air over the curved top creates lower pressure.", "Bernoulli's principle + Newton's third law (wing deflects air downward). Angle of attack: angle between wing and airflow. Too high → stall (airflow separates, lift lost). Flaps increase lift for takeoff/landing. Drag opposes motion; streamlining reduces it.", "engineering"),
  F("Reinforced concrete combines concrete (strong in compression, weak in tension) with steel rebar (strong in tension).", "Concrete: 20-40 MPa compressive strength. Steel: 250-500 MPa yield strength. Rebar ribbed for bond. Pre-stressed concrete: steel tendons tensioned before or after pouring, allowing longer spans and thinner sections. Most widely used construction material globally.", "engineering"),

  // ===== Practical Skills (30) =====
  F("The Maillard reaction is the browning that occurs when amino acids and reducing sugars react at high temperatures (140-165°C).", "Responsible for the flavor of seared steak, toasted bread, roasted coffee, fried onions. Different from caramelization (sugar breaking down). Low moisture needed (why searing requires dry meat). Produces hundreds of flavor compounds.", "practical"),
  F("Emulsification combines two immiscible liquids (oil + water) using an emulsifier (lecithin in egg yolks, mustard).", "Mayonnaise: oil + vinegar + egg yolk. Hollandaise: butter + egg yolks + lemon. Vinaigrette: oil + vinegar + mustard (temporary emulsion). Emulsifiers have hydrophilic (water-loving) and lipophilic (fat-loving) ends that bridge the two phases.", "practical"),
  F("The 50/30/20 budget rule: 50% needs (rent, food, utilities), 30% wants (entertainment, dining), 20% savings/debt repayment.", "Popularized by Elizabeth Warren. Adjust based on income/cost of living. High-cost areas may need 60% needs. Aggressive savers: 30-50% savings. Pay yourself first: automate savings on payday. Emergency fund: 3-6 months expenses before investing.", "practical"),
  F("Compound interest: A = P(1+r/n)^(nt). $1,000 at 7% for 30 years = ~$7,612.", "Start early: $5,000/year from age 25-35 (10 years) > $5,000/year from 35-65 (30 years) at 7% return. Rule of 72: 72/rate = years to double. Index funds (S&P 500): ~10% average annual return historically (~7% inflation-adjusted). Dollar-cost averaging reduces timing risk.", "practical"),
  F("The debt avalanche method pays off highest-interest debt first, saving the most money. The debt snowball pays smallest balance first, for psychological wins.", "Avalanche: mathematically optimal. Snowball: better for motivation (quick wins). Both require minimum payments on all debts + extra payment toward target debt. Balance transfer cards (0% intro APR) can help. Avoid payday loans (300%+ APR).", "practical"),
  F("Progressive overload is the key principle for building muscle: gradually increase weight, reps, or sets over time.", "Muscle grows via repair of micro-tears from resistance. 3-5 sets of 5-12 reps per exercise. Rest 48-72h per muscle group. Protein: 0.7-1g per lb bodyweight. Sleep 7-9h (growth hormone peaks in deep sleep). Track progress (app or journal). Deload every 4-6 weeks.", "practical"),
  F("The Pomodoro technique: work 25 minutes, rest 5 minutes, repeat. After 4 cycles, take a 15-30 minute break.", "Reduces mental fatigue, maintains focus. 25-min sessions feel manageable (low barrier to start). Variations: 50/10 for deep work. Time blocking: schedule specific tasks in specific time slots. GTD (Getting Things Done): capture → clarify → organize → reflect → engage.", "practical"),
  F("STAR method for interviews: Situation, Task, Action, Result. Structure behavioral answers with a specific example.", "Situation: set the context. Task: what you needed to do. Action: what YOU did (not the team). Result: quantifiable outcome ('increased sales 30%'). Prepare 5-7 stories covering: leadership, conflict, failure, teamwork, problem-solving, achievement. Research company values + tailor stories.", "practical"),
  F("To improve sleep quality: maintain consistent schedule, 18-22°C room, no screens 1h before bed (blue light), avoid caffeine after noon, exercise (not too late).", "Adults need 7-9h. Blue light suppresses melatonin (use night mode or blue-light glasses if screens needed). Alcohol disrupts REM (worse sleep quality). Heavy meals before bed cause reflux. White noise or earplugs help. Magnesium supplements may help. If snoring, check for sleep apnea.", "practical"),
  F("To learn any skill faster: practice daily (consistency > intensity), use spaced repetition (Anki) for memorization, teach others, get feedback, break into sub-skills.", "10,000-hour rule (Anders Ericsson): expertise takes ~10,000 hours of deliberate practice. But 20 hours of focused practice gets you 'reasonably good' at most skills (Josh Kaufman). Active recall > re-reading. Interleaving (mixing topics) improves retention vs. blocking.", "practical"),
];

export async function seedGeneralKnowledgeV4(tenantId: string, applicationId: string): Promise<{ sourceId: string; itemCount: number }> {
  const { db } = await import("@/lib/db");
  const { buildTermVector, serializeVector } = await import("./vectors");

  let source = await db.knowledgeSource.findFirst({
    where: { tenantId, title: GENERAL_KNOWLEDGE_SOURCE_V4.title },
  });
  if (!source) {
    source = await db.knowledgeSource.create({
      data: {
        tenantId,
        sourceType: GENERAL_KNOWLEDGE_SOURCE_V4.sourceType,
        title: GENERAL_KNOWLEDGE_SOURCE_V4.title,
        author: GENERAL_KNOWLEDGE_SOURCE_V4.author,
        trustLevel: GENERAL_KNOWLEDGE_SOURCE_V4.trustLevel,
        verificationStatus: GENERAL_KNOWLEDGE_SOURCE_V4.verificationStatus,
        dataClassification: GENERAL_KNOWLEDGE_SOURCE_V4.dataClassification,
      },
    });
  }

  let itemCount = 0;
  for (const k of GENERAL_KNOWLEDGE_BASE_V4) {
    const existing = await db.knowledgeItem.findFirst({
      where: { tenantId, sourceId: source.id, claim: k.claim },
    });
    if (existing) continue;
    await db.knowledgeItem.create({
      data: {
        tenantId,
        applicationId,
        sourceId: source.id,
        type: k.type,
        scope: k.scope ?? "APPLICATION",
        claim: k.claim,
        content: k.content,
        contentVector: serializeVector(buildTermVector(k.claim + " " + k.content)),
        status: "ACTIVE",
        confidence: 0.85,
        validFrom: new Date(),
        refreshSchedule: "manual",
        lastRefreshedAt: new Date(),
      },
    });
    itemCount++;
  }
  return { sourceId: source.id, itemCount };
}
