// WEDJAT BRAIN — Knowledge Base V3 (continued expansion)
// Fills gaps: more countries, more programming, more medicine, more practical,
// current events, more languages, more science. Combined with V1 + V2, the
// Brain has 900+ knowledge items.

export interface KnowledgeSeedItem {
  type: "FACT" | "RULE" | "PROCEDURE" | "OBSERVATION";
  claim: string;
  content: string;
  scope?: "APPLICATION" | "GLOBAL";
  category: string;
  validFrom?: Date;
}

export const GENERAL_KNOWLEDGE_SOURCE_V3 = {
  sourceType: "web",
  title: "General Knowledge Base V3",
  author: "Wedjat Brain",
  trustLevel: "SUPPORTED",
  verificationStatus: "VERIFIED",
  dataClassification: "PUBLIC",
};

function item(type: KnowledgeSeedItem["type"], claim: string, content: string, category: string): KnowledgeSeedItem {
  return { type, claim, content, scope: "APPLICATION", category };
}

export const GENERAL_KNOWLEDGE_BASE_V3: KnowledgeSeedItem[] = [
  // ===== More Countries & Capitals (50) =====
  item("FACT", "Astana (renamed Nur-Sultan 2019-2022, back to Astana) is the capital of Kazakhstan.", "Kazakhstan: 19 million people, largest landlocked country, 9th largest by area. Rich in oil, gas, uranium. Central Asian steppe. Russian + Kazakh official.", "geography"),
  item("FACT", "Tashkent is the capital of Uzbekistan.", "Uzbekistan: 35 million. Doubly landlocked. Silk Road cities: Samarkand, Bukhara, Khiva. Cotton, gold, uranium. Uzbek + Russian.", "geography"),
  item("FACT", "Bishkek is the capital of Kyrgyzstan.", "Kyrgyzstan: 6.7 million. Mountainous (Tian Shan). Nomadic heritage, yurts, eagle hunting. Kyrgyz + Russian. Democratic relative to neighbors.", "geography"),
  item("FACT", "Dushanbe is the capital of Tajikistan.", "Tajikistan: 10 million. Persian-speaking (Tajik). Mountainous (Pamir range — 'Roof of the World'). Cotton, aluminum. Civil war 1992-97.", "geography"),
  item("FACT", "Ashgabat is the capital of Turkmenistan.", "Turkmenistan: 6.4 million. Natural gas reserves (4th largest). White marble city. Authoritarian single-party. Neutral status. Former Soviet.", "geography"),
  item("FACT", "Kabul is the capital of Afghanistan.", "Afghanistan: 41 million. Pashtun, Tajik, Hazara, Uzbek. Dari + Pashto. Taliban took over 2021 after US withdrawal. Mountains, opium production.", "geography"),
  item("FACT", "Beirut is the capital of Lebanon.", "Lebanon: 5.5 million. Religious diversity: Christian, Sunni, Shia, Druze. Civil war 1975-1990. Hezbollah. Economic crisis 2019-present.", "geography"),
  item("FACT", "Damascus is the capital of Syria, one of the oldest continuously inhabited cities in the world.", "Syria: 22 million. Civil war 2011-present. Arab + Kurdish. Arabic. Rich history (Umayyad Mosque, Palmyra). Refugee crisis: 6.8M displaced.", "geography"),
  item("FACT", "Amman is the capital of Jordan.", "Jordan: 11 million. Constitutional monarchy (Hashemite). Hosts Palestinian, Iraqi, Syrian refugees. Petra (lost city), Wadi Rum desert. Stable.", "geography"),
  item("FACT", "Sana'a is the capital of Yemen.", "Yemen: 34 million. Civil war 2014-present (Houthis vs government). Poorest Arab country. Humanitarian crisis. Old Sana'a UNESCO site.", "geography"),
  item("FACT", "Muscat is the capital of Oman.", "Oman: 5.1 million. Absolute monarchy (Sultan). Ibadi Islam. Strategic location (Strait of Hormuz). Oil, frankincense. Moderate foreign policy.", "geography"),
  item("FACT", "Doha is the capital of Qatar.", "Qatar: 2.9 million. Absolute monarchy (Al Thani). Wealthiest per capita (natural gas). Al Jazeera. 2022 FIFA World Cup host. US military base.", "geography"),
  item("FACT", "Manama is the capital of Bahrain.", "Bahrain: 1.5 million. Constitutional monarchy. First Gulf state to discover oil. US Navy 5th Fleet. Shia majority, Sunni ruling. F1 Grand Prix.", "geography"),
  item("FACT", "Kuwait City is the capital of Kuwait.", "Kuwait: 4.5 million. Constitutional monarchy (Al Sabah). Oil reserves (6th largest). 1990 Iraqi invasion → Gulf War. Strong parliament for Gulf.", "geography"),
  item("FACT", "Tripoli is the capital of Libya.", "Libya: 7 million. Oil reserves (9th largest). Gaddafi ruled 1969-2011 (killed in NATO-backed revolution). Civil war since. Berber + Arab.", "geography"),
  item("FACT", "Tunis is the capital of Tunisia.", "Tunisia: 12 million. Arab Spring started here 2010 (Bouazizi). Most democratic Arab country. Mediterranean coast. Phoenician (Carthage), Roman, Arab heritage.", "geography"),
  item("FACT", "Algiers is the capital of Algeria.", "Algeria: 45 million. Largest country by area in Africa. Oil, gas. Independence from France 1962 after 8-year war. Berber (Amazigh) + Arab.", "geography"),
  item("FACT", "Rabat is the capital of Morocco; Casablanca is the largest city.", "Morocco: 37 million. Constitutional monarchy (King Mohammed VI). Arab + Berber. Tourism (Marrakech, Fez, Chefchaouen). Western Sahara dispute. Atlas Mountains.", "geography"),
  item("FACT", "Khartoum is the capital of Sudan.", "Sudan: 47 million. Arab + African. Civil war 2023-present (SAF vs RSF). South Sudan seceded 2011. Oil. Nubian pyramids (Meroë).", "geography"),
  item("FACT", "Juba is the capital of South Sudan, the world's newest country (independent 2011).", "South Sudan: 11 million. Newest UN member. Civil war 2013-2020. Oil. Dinka, Nuer tribes. One of least developed countries.", "geography"),
  item("FACT", "Addis Ababa is the capital of Ethiopia; it hosts the African Union headquarters.", "Ethiopia: 120 million. Never colonized (except 1936-41). Coffee origin. Tigray war 2020-2022. Amharic + Oromo. Orthodox Christian + Muslim.", "geography"),
  item("FACT", "Mogadishu is the capital of Somalia.", "Somalia: 17 million. Civil war since 1991. Piracy. Somaliland (de facto independent). Nomadic, clan-based society. Somali + Arabic.", "geography"),
  item("FACT", "Kampala is the capital of Uganda.", "Uganda: 47 million. Idi Amin's brutal regime 1971-79. Source of Nile. Mountain gorillas (Bwindi). English + Swahili + Luganda.", "geography"),
  item("FACT", "Dar es Salaam (former capital) is the largest city; Dodoma is the capital of Tanzania.", "Tanzania: 65 million. Mount Kilimanjaro, Serengeti, Zanzibar. Swahili + English. Stable politics. Julius Nyerere (father of nation).", "geography"),
  item("FACT", "Luanda is the capital of Angola.", "Angola: 35 million. Portuguese colony until 1975. Civil war 1975-2002. Oil, diamonds. Wealth inequality despite resources.", "geography"),
  item("FACT", "Harare is the capital of Zimbabwe.", "Zimbabwe: 16 million. Robert Mugabe ruled 1980-2017. Hyperinflation (2008: 79.6 billion %). Victoria Falls. Shona majority. Land reform controversy.", "geography"),
  item("FACT", "Lusaka is the capital of Zambia.", "Zambia: 20 million. Copper reserves. Victoria Falls (shared with Zimbabwe). Peaceful independence 1964. One of Africa's stable democracies.", "geography"),
  item("FACT", "Maputo is the capital of Mozambique.", "Mozambique: 33 million. Portuguese colony until 1975. Civil war 1977-92. Cyclones, insurgency in north. Bantu peoples. Swahili coast.", "geography"),
  item("FACT", "Antananarivo is the capital of Madagascar.", "Madagascar: 29 million. 4th largest island. 90% wildlife endemic (lemurs, baobab). Malagasy + French. Biodiversity hotspot.", "geography"),
  item("FACT", "Port Louis is the capital of Mauritius.", "Mauritius: 1.3 million. Island nation. Dodo (extinct). Indo-Mauritian, Creole, Sino-Mauritian, Franco. High-income economy. Beaches, reefs.", "geography"),
  item("FACT", "Yerevan is the capital of Armenia.", "Armenia: 2.8 million. First Christian nation (301 AD). Genocide 1915 (1.5M killed by Ottomans). Nagorno-Karabakh conflict. Diaspora ~8M.", "geography"),
  item("FACT", "Baku is the capital of Azerbaijan.", "Azerbaijan: 10 million. Oil-rich (Caspian Sea). Shi'a Muslim, secular state. Nagorno-Karabakh conflict with Armenia. Turkic language.", "geography"),
  item("FACT", "Tbilisi is the capital of Georgia.", "Georgia: 3.7 million. Caucasus. Wine origin (8000 years). Russian invasion 2008. Orthodox Christian. Georgian alphabet unique.", "geography"),
  item("FACT", "Reykjavik is the capital of Iceland.", "Iceland: 375,000. Volcanic island. Geothermal energy. Oldest parliament (Althingi, 930 AD). High standard of living. NATO, no EU. Krona currency.", "geography"),
  item("FACT", "Tallinn is the capital of Estonia.", "Estonia: 1.3 million. EU + NATO. Estonian (Finnic). Digital society (e-residency). Skype origin. Singing Revolution (1987-91).", "geography"),
  item("FACT", "Riga is the capital of Latvia.", "Latvia: 1.9 million. EU + NATO. Latvian (Baltic). Russian minority ~25%. Art Nouveau architecture. Forests cover 50% of land.", "geography"),
  item("FACT", "Vilnius is the capital of Lithuania.", "Lithuania: 2.8 million. EU + NATO. Largest Baltic state. Basketball-crazy. First Soviet republic to declare independence (1990).", "geography"),
  item("FACT", "Bratislava is the capital of Slovakia.", "Slovakia: 5.5 million. EU + NATO. Car manufacturing. Tatra mountains. Velvet Divorce with Czech Republic 1993.", "geography"),
  item("FACT", "Ljubljana is the capital of Slovenia.", "Slovenia: 2.1 million. EU + NATO. Most affluent ex-Yugoslav. Alps, caves, coast. Bee symbolizes nation. First ex-Yugoslav to join EU (2004).", "geography"),
  item("FACT", "Zagreb is the capital of Croatia.", "Croatia: 3.9 million. EU (2013) + NATO. Coastline (Adriatic). Tourism (Dubrovnik, Plitvice lakes). War of independence 1991-95. Euro + Schengen 2023.", "geography"),
  item("FACT", "Sarajevo is the capital of Bosnia and Herzegovina.", "Bosnia: 3.2 million. 1992-95 war. Three main groups: Bosniaks, Serbs, Croats. Complex power-sharing. Archduke Franz Ferdinand assassinated here 1914.", "geography"),
  item("FACT", "Belgrade is the capital of Serbia.", "Serbia: 6.7 million. EU candidate. Kosovo dispute (declared independence 2008). Cyrillic alphabet. Nikola Tesla. Former Yugoslavia capital.", "geography"),
  item("FACT", "Pristina is the capital of Kosovo.", "Kosovo: 1.8 million. Declared independence 2008 (recognized by ~100 countries, not by Serbia, Russia, China). Albanian majority. Youngest European state.", "geography"),
  item("FACT", "Skopje is the capital of North Macedonia.", "North Macedonia: 1.8 million. NATO (2020), EU candidate. Name dispute with Greece resolved 2019 (added 'North'). Alexander the Great heritage.", "geography"),
  item("FACT", "Tirana is the capital of Albania.", "Albania: 2.8 million. EU candidate. Communist until 1991. Albanian language unique (Indo-European but distinct). Bunkers everywhere (Enver Hoxha paranoia).", "geography"),
  item("FACT", "Chisinau is the capital of Moldova.", "Moldova: 2.6 million. Poorest EU candidate. Wine industry. Romanian-speaking. Transnistria breakaway (Russian-backed). EU candidate 2022.", "geography"),
  item("FACT", "Minsk is the capital of Belarus.", "Belarus: 9.2 million. Authoritarian (Lukashenko since 1994). Russian-aligned. Chernobyl-affected. Not EU. 2020 protests crushed.", "geography"),
  item("FACT", "Valletta is the capital of Malta.", "Malta: 535,000. Smallest EU state. Islands. Phoenician, Roman, Arab, Knights Hospitaller, British heritage. English + Maltese (Semitic). Tourism.", "geography"),
  item("FACT", "Nicosia is the capital of Cyprus, the world's last divided capital.", "Cyprus: 1.2 million. EU. Divided since 1974: Greek Cypriot south (recognized), Turkish Cypriot north (only Turkey recognizes). British bases.", "geography"),
  item("FACT", "Brussels is the capital of Belgium and the de facto capital of the European Union.", "Belgium: 11.7 million. EU + NATO HQ. Trilingual: Dutch (Flanders), French (Wallonia), German. Flemish-Walloon tension. Waffles, chocolate, beer.", "geography"),
  item("FACT", "Bern is the capital of Switzerland; Zurich and Geneva are larger cities.", "Switzerland: 8.8 million. Not EU. Neutral. Cantons (26). Direct democracy. Banks, watches, chocolate. 4 languages: German, French, Italian, Romansh.", "geography"),

  // ===== Advanced Programming (40) =====
  item("FACT", "Time complexity of common data structure operations: array access O(1), linked list search O(n), hash table lookup average O(1), BST search O(log n) balanced.", "Understanding complexity guides algorithm choice. Arrays for random access, linked lists for insertion, hash tables for fast lookup, balanced trees for sorted data.", "programming"),
  item("FACT", "The CAP theorem states a distributed system can provide at most 2 of: Consistency, Availability, Partition tolerance.", "In network partitions (P), choose C (block) or A (serve possibly-stale). CP systems: HBase, MongoDB. AP: Cassandra, DynamoDB. PACELC extends CAP for latency when no partition.", "programming"),
  item("FACT", "ACID properties guarantee reliable database transactions: Atomicity, Consistency, Isolation, Durability.", "Atomic: all or nothing. Consistent: valid state. Isolated: concurrent transactions don't interfere. Durable: committed data survives crashes. SQL DBs default ACID. NoSQL often BASE (Basically Available, Soft state, Eventual consistency).", "programming"),
  item("FACT", "SOLID principles: Single responsibility, Open/closed, Liskov substitution, Interface segregation, Dependency inversion.", "Robert C. Martin. Single: class does one thing. Open-closed: extend don't modify. Liskov: subtypes replaceable. Interface segregation: many specific interfaces. Dependency inversion: depend on abstractions.", "programming"),
  item("FACT", "Design patterns are reusable solutions: Singleton (one instance), Factory (create objects), Observer (pub-sub), Strategy (interchangeable algorithms), Decorator (add behavior).", "Gang of Four book (1994): 23 patterns. Creational, structural, behavioral categories. Don't over-apply — patterns add complexity.", "programming"),
  item("FACT", "REST API design: resources are nouns (/users/123), HTTP methods are verbs (GET/POST/PUT/DELETE), stateless, use status codes (200, 201, 400, 404, 500).", "Best practices: version APIs (/v1/users), paginate large responses, use HATEOAS for discoverability, idempotency keys for POST, OAuth2 for auth, rate limiting.", "programming"),
  item("FACT", "GraphQL is a query language for APIs that lets clients request exactly the data they need.", "Single endpoint. Strongly typed schema. Solves over-fetching (REST returns fixed fields) and under-fetching (REST needs multiple calls). Used by Facebook, GitHub, Shopify.", "programming"),
  item("FACT", "WebSocket enables full-duplex communication over a single TCP connection, unlike HTTP's request-response model.", "Used for chat, live updates, gaming, collaboration. Server can push data without client polling. wss:// is encrypted. Falls back to long-polling if blocked.", "programming"),
  item("FACT", "Microservices architecture splits an app into small, independently deployable services.", "Pros: independent scaling, tech diversity, fault isolation. Cons: distributed complexity, network latency, harder debugging, data consistency. Monolith-first often recommended.", "programming"),
  item("FACT", "CI/CD (Continuous Integration / Continuous Deployment) automates build, test, and deploy.", "CI: every commit triggers automated build + tests. CD: automatic deployment to staging/production. Tools: Jenkins, GitHub Actions, GitLab CI, CircleCI. Enables small, frequent, safe releases.", "programming"),
  item("FACT", "The 12-factor app methodology guides building SaaS apps: codebase, dependencies, config, backing services, build/release/run, processes, port binding, concurrency, disposability, dev/prod parity, logs, admin processes.", "Heroku (2011). Best practices for cloud-native apps. Separates config from code, treats logs as event streams, keeps processes stateless.", "programming"),
  item("FACT", "JWT (JSON Web Token) is a compact, self-contained token for authentication.", "Three parts: header.algorithm+type, payload.claims, signature. Stateless: server doesn't store sessions. Signed (HMAC or RSA). Use HTTPS. Short expiry + refresh token for security.", "programming"),
  item("FACT", "OAuth 2.0 is an authorization framework letting third-party apps access user data without sharing passwords.", "Flows: authorization code (web), implicit (deprecated), client credentials (server-to-server), password (legacy), refresh token. Used by 'Login with Google/Facebook/GitHub'.", "programming"),
  item("FACT", "The MVC pattern separates Model (data), View (UI), Controller (logic).", "Improves maintainability, testability, separation of concerns. Variations: MVP (Presenter), MVVM (ViewModel — used in Vue/Knockout). Rails, Django, Spring MVC use it.", "programming"),
  item("FACT", "React is a JavaScript library for building UIs using components and a virtual DOM.", "Facebook (2013). Components are reusable. Virtual DOM diffs before real DOM updates (efficient). JSX syntax. Hooks (useState, useEffect). React Native for mobile.", "programming"),
  item("FACT", "Vue.js is a progressive JavaScript framework for UIs, combining template-based rendering with reactivity.", "Evan You (2014). Easier learning curve than React. Single-file components (.vue). Composition API (Vue 3). Used by Alibaba, GitLab, Adobe.", "programming"),
  item("FACT", "Angular is a TypeScript-based web framework by Google, with dependency injection, RxJS, and a complete MVC architecture.", "Opinionated, batteries-included. Modules, components, services. Two-way data binding. Steeper learning curve than React/Vue. Used by Google, Microsoft.", "programming"),
  item("FACT", "Node.js is a JavaScript runtime built on Chrome's V8 engine, enabling server-side JS.", "Ryan Dahl (2009). Event-driven, non-blocking I/O (libuv). Single-threaded but handles many connections via event loop. npm has 2M+ packages. Used for APIs, real-time apps.", "programming"),
  item("FACT", "The event loop in JavaScript handles asynchronous operations via a queue + call stack.", "Single-threaded but non-blocking. Microtask queue (Promises) has priority over macrotask queue (setTimeout, I/O). Understanding it explains async behavior, deadlocks, performance.", "programming"),
  item("FACT", "Python is a high-level, interpreted language known for readability and used heavily in AI/data science.", "Guido van Rossum (1991). Indentation-based syntax. Dynamically typed. Batteries included (stdlib). NumPy, pandas, scikit-learn, PyTorch, TensorFlow. 2nd most popular language.", "programming"),
  item("FACT", "TypeScript is a typed superset of JavaScript that compiles to plain JavaScript.", "Microsoft (2012). Adds static types, interfaces, generics. Catches errors at compile time. Popular for large codebases. Used by Angular, VS Code, Slack.", "programming"),
  item("FACT", "Rust is a systems programming language focused on memory safety without a garbage collector.", "Mozilla (2010). Ownership + borrowing system prevents memory bugs at compile time. No null, no data races. Steep learning curve but beloved (most-loved language 7 years running).", "programming"),
  item("FACT", "Go (Golang) is a compiled, statically typed language by Google, designed for simplicity and concurrency.", "2009. Goroutines (lightweight threads), channels for communication. Fast compilation. Used by Docker, Kubernetes, Terraform. No classes, no exceptions (error returns).", "programming"),
  item("FACT", "Java is a class-based, object-oriented language with 'write once, run anywhere' via JVM.", "Sun Microsystems (1995, now Oracle). Strong typing, automatic garbage collection. Huge ecosystem (Spring, Hadoop, Android). Verbose but stable. 3 billion+ devices run Java.", "programming"),
  item("FACT", "C++ is a compiled, general-purpose language with OOP, generic programming, and low-level memory control.", "Bjarne Stroustrup (1985). Extends C with classes, templates, exceptions. Used for OS, games (Unreal Engine), browsers, databases. Complex but performant.", "programming"),
  item("FACT", "Linux is an open-source Unix-like kernel; popular distributions include Ubuntu, Debian, CentOS, Fedora, Arch.", "Linus Torvalds (1991). Powers most servers, supercomputers, Android phones. GNU/Linux is the full OS. Package managers: apt (Debian), yum/dnf (Red Hat), pacman (Arch).", "programming"),
  item("FACT", "Git branching strategies: Git Flow (master/develop/feature/release/hotfix), GitHub Flow (main + feature branches), Trunk-based (commit directly to main).", "Git Flow: complex, releases. GitHub Flow: simple, continuous deployment. Trunk-based: fast, requires CI/CD, feature flags. Choice depends on team + deployment cadence.", "programming"),
  item("FACT", "The SOLID tradeoff: more abstraction = more flexibility but also more complexity.", "Don't abstract prematurely. Rule of three: abstract only after similar code appears 3 times. YAGNI: don't build what you don't need yet.", "programming"),
  item("FACT", "Big O notation examples: O(1) — array access, hash lookup. O(log n) — binary search. O(n) — linear scan. O(n log n) — merge sort. O(n²) — bubble sort, nested loops. O(2^n) — naive Fibonacci.", "Choose algorithms by complexity. For n=1M: O(1) instant, O(log n) ~20 ops, O(n) 1M ops, O(n²) 10^12 ops (too slow). Profile before optimizing.", "programming"),
  item("FACT", "Recursion depth limit in JavaScript is typically ~10,000 frames; deep recursion causes stack overflow.", "Tail call optimization (TCO) can help but isn't widely supported. Convert deep recursion to iteration for safety. Some languages (Scheme) guarantee TCO.", "programming"),
  item("FACT", "A linked list has O(1) insertion/deletion at known positions, but O(n) random access.", "vs array: O(1) random access but O(n) middle insert/delete. Use linked list when frequent insert/delete at ends/middle; use array for random access. Cache locality favors arrays.", "programming"),
  item("FACT", "Hash collision resolution: chaining (linked list per bucket) or open addressing (probe for empty slot).", "Chaining: simple, handles high load factors. Open addressing: better cache performance, probing strategies (linear, quadratic, double hashing). Load factor >0.7 degrades performance.", "programming"),
  item("FACT", "The observer pattern: a subject maintains a list of dependents (observers) and notifies them of state changes.", "Used in event systems, MVC (model notifies views), RxJS, message queues. Pub-sub is a variant (decoupled via broker).", "programming"),
  item("FACT", "Dependency injection (DI) is a pattern where objects receive dependencies rather than creating them.", "Improves testability (mock deps), modularity. Frameworks: Spring (Java), Angular, NestJS. Inversion of control (IoC) is the broader principle.", "programming"),
  item("FACT", "The single responsibility principle: a class should have only one reason to change.", "Robert C. Martin. Separation of concerns. E.g., a User class shouldn't also handle email sending. Smaller focused classes are easier to test and maintain.", "programming"),
  item("FACT", "Clean code principles: meaningful names, small functions (do one thing), comments explain why not what, avoid deep nesting, DRY (Don't Repeat Yourself).", "Robert C. Martin. Readable code is maintainable code. Code is read 10x more than written. Refactor continuously. Tests enable safe refactoring.", "programming"),
  item("FACT", "Test-driven development (TDD): Red (write failing test) → Green (make it pass) → Refactor.", "Kent Beck. Forces clear requirements, ensures test coverage, improves design. Hard to apply everywhere (UI, legacy). Acceptance TDD for behavior, unit TDD for code.", "programming"),
  item("FACT", "Code review best practices: small PRs (<400 lines), clear description, review within 24h, be kind, suggest not demand, use a checklist.", "Catches bugs, spreads knowledge, enforces standards. Automated checks (lint, tests, security) reduce review burden. 2 reviewers ideal.", "programming"),
  item("FACT", "Common DevOps practices: infrastructure as code (Terraform), containers (Docker), orchestration (Kubernetes), monitoring (Prometheus + Grafana), logging (ELK/EFK).", "Goal: ship faster, more reliably. CI/CD pipeline. Blue-green or canary deployments. Observability (logs, metrics, traces). SRE practices.", "programming"),
  item("FACT", "Prometheus is a monitoring system with a time-series database; Grafana visualizes metrics; the ELK stack (Elasticsearch, Logstash, Kibana) handles logs.", "Three pillars of observability: metrics (numbers over time), logs (events), traces (request flow). OpenTelemetry is the emerging standard.", "programming"),

  // ===== More Science (30) =====
  item("FACT", "The human eye can distinguish about 10 million colors, with three types of cone cells (red, green, blue).", "Cones work in bright light. Rods (~120M per eye) work in dim light but don't detect color. Color blindness (8% of men) usually affects red-green cones.", "science"),
  item("FACT", "Sound travels at about 343 m/s in air (at 20°C), much slower than light (~300,000,000 m/s).", "This is why we see lightning before hearing thunder (~3 seconds per km). Sound speed: 343 m/s air, 1480 m/s water, 5960 m/s steel. Higher in solids (molecules closer).", "science"),
  item("FACT", "A lightning bolt is about 5 times hotter than the Sun's surface (~30,000°C vs ~5,500°C).", "The massive electrical current heats air rapidly, expanding it → thunder. A bolt carries ~100 million volts, ~30,000 amps. Strikes Earth ~8 million times/day.", "science"),
  item("FACT", "The Earth's inner core is solid iron-nickel at ~5,400°C; the outer core is liquid, generating the magnetic field.", "Inner core (solid): 1,220 km radius. Outer core (liquid): 2,260 km thick. Mantle: 2,900 km. Crust: 5-70 km. Convection in outer core → geodynamo → magnetic field.", "science"),
  item("FACT", "The Earth's magnetic field protects us from solar wind; it reverses every ~200,000-300,000 years.", "Last reversal was 780,000 years ago (Brunhes-Matuyama). Magnetic north moves ~50 km/year currently. Weakens during reversal but doesn't disappear. Auroras at poles.", "science"),
  item("FACT", "Photosynthesis produces glucose and oxygen from CO2 and water using sunlight: 6CO2 + 6H2O + light → C6H12O6 + 6O2.", "Chlorophyll absorbs red + blue light, reflects green (why plants look green). Two stages: light reactions (thylakoid membranes, ATP/NADPH/O2) + Calvin cycle (stroma, glucose).", "science"),
  item("FACT", "The human body contains about 37 trillion cells, each with ~2 meters of DNA if stretched out.", "Total DNA per body cell: ~2m. With 37T cells, total DNA length could stretch to Sun and back ~60 times. Most cells (except RBCs) contain a nucleus with DNA.", "science"),
  item("FACT", "Mitochondria are the 'powerhouses' of the cell, generating ATP via cellular respiration.", "Have their own DNA (maternal inheritance). Endosymbiotic theory: ancient bacteria engulfed by cells. ~1000-2000 per cell. Muscles have more (high energy demand).", "science"),
  item("FACT", "The Krebs cycle (citric acid cycle) occurs in mitochondria, producing NADH and FADH2 for the electron transport chain.", "Discovered by Hans Krebs (1937). Each glucose yields 2 ATP (glycolysis) + 2 ATP (Krebs) + ~32 ATP (ETC). 8 Krebs intermediate reactions, fully cyclic.", "science"),
  item("FACT", "CRISPR-Cas9 was adapted from bacteria's immune system that 'remembers' viral DNA.", "Bacteria store snippets of viral DNA between CRISPR repeats. On reinfection, guide RNA matches viral DNA, Cas9 cuts it. Repurposed for gene editing (Doudna, Charpentier, 2020 Nobel).", "science"),
  item("FACT", "A protein's function depends on its 3D shape, determined by its amino acid sequence.", "Primary: sequence. Secondary: α-helix, β-sheet (hydrogen bonds). Tertiary: full 3D fold. Quaternary: multiple subunits. Misfolding causes Alzheimer's, Parkinson's, prion diseases.", "science"),
  item("FACT", "Stem cells can differentiate into any cell type; embryonic stem cells are pluripotent, adult stem cells are multipotent.", "iPSCs (induced pluripotent stem cells) — Yamanaka (2007, Nobel 2012): adult cells reprogrammed to embryonic-like. Potential for regenerative medicine, disease modeling.", "science"),
  item("FACT", "A calorie (small calorie) is the energy to heat 1g water by 1°C; food Calories are kilocalories (1000 small calories).", "1 kcal = 4184 joules. Carbs/protein: 4 kcal/g. Fat: 9 kcal/g. Alcohol: 7 kcal/g. Adult needs ~2000-2500 kcal/day depending on activity. Diet labels use Cal (kcal).", "science"),
  item("FACT", "The atmosphere has 5 layers: troposphere (weather, 0-12km), stratosphere (ozone, 12-50km), mesosphere (meteors, 50-85km), thermosphere (auroras, 85-600km), exosphere (space, 600-10000km).", "Temperature varies oddly: decreases in troposphere, increases in stratosphere (ozone absorbs UV), decreases in mesosphere, increases in thermosphere (UV absorption).", "science"),
  item("FACT", "The water cycle: evaporation (water→vapor), condensation (vapor→clouds), precipitation (rain/snow), collection (rivers/oceans), then repeats.", "Driven by Sun. ~97% of water is salty (oceans). ~3% fresh, but 2/3 is ice (glaciers). Only ~1% accessible freshwater. Water scarcity affects 2B+ people.", "science"),
  item("FACT", "Carbon has 4 valence electrons, allowing it to form 4 bonds — basis of organic chemistry and life.", "Can bond with itself (chains, rings, branches) + H, O, N, S, P. Forms single, double, triple bonds. Allotropes: diamond (hard, transparent), graphite (soft, conductive), graphene, fullerenes.", "science"),
  item("FACT", "Radioactive decay is the spontaneous emission of particles/energy from unstable atomic nuclei.", "Three types: alpha (He nucleus, stopped by paper), beta (electron, stopped by aluminum), gamma (photon, stopped by lead). Half-life: time for half of atoms to decay. Dating: C-14 (50k years), U-238 (4.5B years).", "science"),
  item("FACT", "Nuclear fission splits heavy atoms (uranium, plutonium) releasing energy; fusion combines light atoms (hydrogen) releasing more energy.", "Fission: current nuclear power plants, atomic bombs (Hiroshima/Nagasaki). Fusion: powers Sun/stars, hydrogen bombs, experimental reactors (ITER). Fusion is cleaner but harder to achieve.", "science"),
  item("FACT", "The Sun produces energy via nuclear fusion: 4 hydrogen nuclei → 1 helium nucleus + energy (E=mc²).", "~600M tonnes of H → 596M tonnes He per second. Missing 4M tonnes → energy (E=mc²). Sun is 4.6B years old, halfway through its hydrogen. Will become red giant in ~5B years.", "science"),
  item("FACT", "Earth's seasons are caused by the 23.5° axial tilt, not distance from the Sun.", "Summer hemisphere: tilted toward Sun → more direct light, longer days. Winter: tilted away. Earth is actually closest to Sun (perihelion) in January (Northern winter).", "science"),
  item("FACT", "Tides are caused by the Moon's gravity pulling Earth's water, creating bulges that rotate as Earth spins.", "Two high tides per day (one facing Moon, one opposite). Sun also affects tides (40% of Moon's effect). Spring tides (highest) at new/full moon. Neap tides (lowest) at quarter moons.", "science"),
  item("FACT", "The Earth's tectonic plates move at 2-15 cm/year, about the speed fingernails grow.", "Plates meet at boundaries: divergent (Mid-Atlantic Ridge, new crust), convergent (Himalayas, subduction), transform (San Andreas, slip). Earthquakes, volcanoes, mountains at boundaries.", "science"),
  item("FACT", "Earthquakes release energy as seismic waves: P-waves (fastest, compress), S-waves (slower, shear), surface waves (slowest, most destructive).", "Measured on Richter scale (logarithmic, magnitude) or Mercalli (intensity). Focus = origin, epicenter = surface point above. >7 magnitude is major. ~500K quakes/year, ~100 cause damage.", "science"),
  item("FACT", "Volcanoes form at plate boundaries (Pacific Ring of Fire) and hotspots (Hawaii, Yellowstone).", "Magma rises from mantle through crust. Types: shield (gentle, basaltic — Hawaii), stratovolcano (explosive, andesitic — Mt St Helens), caldera (huge collapse — Yellowstone).", "science"),
  item("FACT", "The ozone layer (stratosphere) absorbs 97-99% of UV radiation; its hole was caused by CFCs.", "CFCs (refrigerants) released Cl that destroyed ozone. Montreal Protocol (1987) phased out CFCs. Hole is recovering, expected healed by 2060. Success story of international cooperation.", "science"),
  item("FACT", "Greenhouse gases: CO2, methane (CH4), nitrous oxide (N2O), water vapor, CFCs.", "CO2: ~76% of warming, lasts centuries. CH4: 28x warming of CO2, lasts ~12 years. N2O: 265x, lasts 114 years. Sources: fossil fuels, agriculture, deforestation, industry.", "science"),
  item("FACT", "The pH scale measures acidity/alkalinity: 0-14, 7 neutral. Battery acid pH 0, lemon 2, water 7, blood 7.4, bleach 13.", "Logarithmic: pH 3 is 10x more acidic than pH 4. Acids release H+, bases release OH-. Stomach acid (HCl) pH 1-2. Soil pH affects plants. Acid rain <5.6.", "science"),
  item("FACT", "Sodium (Na) is highly reactive (explodes in water); sodium chloride (table salt) is stable.", "Properties change when elements combine. NaCl dissolves into Na+ and Cl- ions, essential for nerve impulses. Too much NaCl raises blood pressure. Recommended: <2300mg/day.", "science"),
  item("FACT", "Diamonds form under extreme pressure/temperature deep in Earth's mantle, brought up by volcanic eruptions.", "Pure carbon, hardest natural material. Industrial uses (cutting, drilling). Synthetic diamonds (HPHT, CVD) now common. Largest: Cullinan (3106 carats, 1905).", "science"),
  item("FACT", "Gold is rare because it only forms in supernovae and neutron star collisions (r-process).", "Unlike lighter elements (formed in stars), heavy elements need extreme conditions. Earth's gold sank to core during formation. All mined gold would fit in a 22m cube.", "science"),

  // ===== More Practical / Everyday (30) =====
  item("FACT", "To tie a tie: the four-in-hand knot is the simplest — wrap wide end around narrow, through loop, down through front.", "Other knots: Windsor (formal, larger), half-Windsor (medium), Pratt/Shelby. Practice makes perfect. The dimple under the knot looks polished.", "practical"),
  item("FACT", "To swim freestyle (front crawl): alternate arm pulls + flutter kick + side breathing every 2-3 strokes.", "Most efficient stroke. Body rotation key. Breathing: exhale underwater, inhale by turning head (not lifting). Practice with a kickboard first.", "practical"),
  item("FACT", "To ride a bicycle: balance by steering into falls, pedal to maintain momentum, brake gently with both brakes.", "Countersteering: to turn right, briefly steer left (counterintuitive). Helmets reduce head injury risk by 60%. Watch for doors (dooring) in cities.", "practical"),
  item("FACT", "To do CPR on a child (1-8 years): use one hand, compress 1/3 chest depth (~2 inches), 100-120/min, 30:2 ratio.", "For infants (<1 year): two fingers, 1.5 inches deep. Rescue breaths: gentle puffs. If alone, do 2 min CPR before calling 911 for children.", "practical"),
  item("FACT", "To remove a stain: blot (don't rub), identify stain type (protein, oil, tannin, dye), treat accordingly.", "Protein (blood, dairy): cold water, enzyme detergent. Oil (grease): dish soap, hot water. Tannin (wine, coffee): vinegar, salt. Dye: rubbing alcohol. Always test on hidden area first.", "practical"),
  item("FACT", "To jump-start a car: connect red (+) to dead battery's red, then to good battery's red; black (-) to good battery's black, then to engine block of dead car.", "Start good car, wait 5 min, start dead car. Remove in reverse order. Never connect black to dead battery's negative (spark risk near hydrogen gas).", "practical"),
  item("FACT", "To parallel park: signal, pull alongside front car (2 ft gap), reverse turning wheel toward curb, straighten when at 45°, then turn away to swing front in.", "Practice makes perfect. Aim 6-12 inches from curb. Adjust forward to center between cars. Don't block driveways or fire hydrants.", "practical"),
  item("FACT", "To write a check: date, payee name, amount in numbers, amount in words, signature, optional memo.", "Amount in words prevents fraud. Sign last. Keep register for tracking. Checks declining but still used for rent, business. Void if error — write 'VOID' and tear up.", "practical"),
  item("FACT", "To create a budget: list income, track all expenses for a month, categorize (needs/wants/savings), set limits, review monthly.", "50/30/20 rule: 50% needs (rent, food), 30% wants (entertainment), 20% savings/debt. Apps: Mint, YNAB, EveryDollar. Pay yourself first (automate savings).", "practical"),
  item("FACT", "To invest for retirement: start early (compound interest), use tax-advantaged accounts (401k, IRA), diversify (index funds), keep fees low.", "S&P 500 averaged ~10%/year historically (~7% inflation-adjusted). 401k employer match is free money. Rule of 72: 72/return = years to double. Target date funds simplify.", "practical"),
  item("FACT", "To lose weight sustainably: create a calorie deficit (500/day = 1 lb/week), eat more protein + fiber, exercise, sleep, manage stress.", "Avoid crash diets (lose muscle, regain fat). Aim for 1-2 lb/week. Track with app (MyFitnessPal). Strength training preserves muscle. Crash diets fail long-term.", "practical"),
  item("FACT", "To build muscle: progressive overload (increase weight/reps), eat 0.7-1g protein per lb bodyweight, rest 48h per muscle group, sleep 7-9h.", "3-5 sets of 5-12 reps per exercise. Compound lifts (squat, deadlift, bench, rows) most efficient. Track progress. Deload every 4-6 weeks. Consistency > intensity.", "practical"),
  item("FACT", "To meditate: sit comfortably, focus on breath (in/out), when mind wanders (it will), gently return attention, start with 5-10 min daily.", "Types: mindfulness (present moment), loving-kindness (compassion), body scan, walking meditation. Apps: Headspace, Calm, Insight Timer. Benefits: stress, focus, emotional regulation.", "practical"),
  item("FACT", "To improve sleep: keep a consistent schedule, dark cool room, no screens 1h before bed, avoid caffeine after noon, exercise (not too late).", "Adults need 7-9h. Blue light suppresses melatonin. Alcohol disrupts REM. Snoring may indicate sleep apnea (see doctor). Naps <30 min OK; longer cause grogginess.", "practical"),
  item("FACT", "To learn a language: immerse (music, movies, podcasts), use spaced repetition (Anki) for vocab, speak from day 1, take classes, find a tutor.", "CEFR levels: A1 (beginner) to C2 (fluent). ~600 hours to fluency for English speakers learning similar languages (Spanish, French). Apps: Duolingo (gamified), Babbel, Pimsleur.", "practical"),
  item("FACT", "To cook pasta: boil 4L water per 500g, salt generously (tastes of sea), add pasta, stir, cook 8-12 min until al dente, reserve some pasta water for sauce.", "Al dente = 'to the tooth' (slight resistance). Don't add oil (prevents sauce sticking). Fresh pasta cooks in 2-4 min. Save pasta water (starch helps sauce cling).", "practical"),
  item("FACT", "To bake bread: mix flour, water, yeast, salt; knead 10 min; rise 1-2h until doubled; shape; rise again 30-60 min; bake 200-230°C for 25-45 min.", "Yeast ferments sugar → CO2 (rises bread) + alcohol (evaporates). Kneading develops gluten. Sourdough uses wild yeast + bacteria (lactic acid). Tap bottom — hollow sound = done.", "practical"),
  item("FACT", "To grow tomatoes: full sun (6+ hours), well-drained soil, water consistently, stake/cage for support, fertilize, prune suckers.", "Plant after last frost. Deep planting (bury stem) develops roots. Determinate (bush, all at once) vs indeterminate (vining, all season). Common problems: blossom-end rot (calcium), blight.", "practical"),
  item("FACT", "To start a garden: test soil, choose easy plants (radishes, lettuce, herbs, tomatoes), water deeply 1-2x/week, mulch to retain moisture.", "Containers work if no ground. Compost improves any soil. Companion planting (basil + tomato) helps. Water morning (less evaporation, prevents fungal disease).", "practical"),
  item("FACT", "To assemble flat-pack furniture: read instructions fully, inventory all parts, use the right tools, don't over-tighten, assemble on a soft surface to prevent scratches.", "IKEA, etc. Empty all boxes first. Sort hardware. Hand-tighten until all aligned, then final-tighten. Keep extra parts. Take photos before disassembling for moving.", "practical"),
  item("FACT", "To fix a leaky faucet: turn off water, remove handle, replace washer/O-ring (usually the culprit), reassemble, test.", "Compression faucets leak when washer wears out. Cartridge faucets need cartridge replacement. Bring old part to store for match. Plumbers grease helps O-rings seat.", "practical"),
  item("FACT", "To fix a running toilet: check flapper (replace if warped/encoded), adjust chain (1/2 inch slack), check fill valve, water level 1/2 inch below overflow tube.", "Most common cause: bad flapper ($5 fix). Continuous running wastes ~200 gallons/day. Check by adding food coloring to tank (if appears in bowl without flushing, leak).", "practical"),
  item("FACT", "To organize a closet: declutter first (keep/donate/trash), group by type/color, use uniform hangers, add shelves/drawers, store off-season separately.", "Marie Kondo: keep only what 'sparks joy'. Hang clothes facing same direction. File-fold t-shirts (vertical) to see all. Store heavy items low, light high.", "practical"),
  item("FACT", "To pack for travel: roll clothes (saves space, fewer wrinkles), use packing cubes, put heavy items at bottom, pack toiletries in ziplock, carry essentials in carry-on.", "Check baggage rules (TSA 3-1-1 for liquids). Wear bulkiest items on plane. Photograph contents for insurance. Leave room for souvenirs. Charger + documents always in carry-on.", "practical"),
  item("FACT", "To negotiate: prepare (know your value/limits), listen, ask open questions, anchor first (if confident), find mutual gain, be willing to walk.", "BATNA (Best Alternative To Negotiated Agreement) = your fallback. Aim high but realistic. Silence is powerful. 'Is that the best you can do?' often improves offer. Win-win > win-lose.", "practical"),
  item("FACT", "To give a presentation: know audience, structure (hook → main points → recap), practice out loud, use visuals sparingly, make eye contact, end strong.", "Rule of 3 (three main points stick). 10-20-30 rule (Kawasaki): 10 slides, 20 min, 30+ font. Stories engage more than data. Pause instead of 'um'. Q&A preparation matters.", "practical"),
  item("FACT", "To write a resume: 1 page (early career) or 2 (senior), action verbs (led, built, increased), quantify achievements (e.g. 'increased sales 30%'), tailor to each job.", "Reverse chronological format most common. ATS (Applicant Tracking Systems) prefer simple formatting. Keywords from job description. No photo (US), expected in some countries.", "practical"),
  item("FACT", "To prepare for a job interview: research company, prepare STAR stories (Situation, Task, Action, Result), dress appropriately, prepare questions, send thank-you note.", "STAR format structures behavioral answers. Research: recent news, values, products, competitors. Questions: 'What does success look like?' Practice with mock interviews.", "practical"),
  item("FACT", "To do a software/code interview: clarify problem, state brute force, optimize, code clean, test with examples, discuss complexity.", "Speak your thoughts. Don't silently code. Edge cases: empty, single, negative, duplicates, overflow. Most interviews care about problem-solving process, not perfect code.", "practical"),
  item("FACT", "To manage stress: exercise regularly, sleep enough, meditation/breathing, social support, limit caffeine/alcohol, set boundaries, seek professional help if needed.", "4-7-8 breathing: inhale 4s, hold 7s, exhale 8s. Box breathing: 4-4-4-4. Mindfulness apps. Time in nature. Chronic stress raises cortisol → health problems. Therapy works.", "practical"),

  // ===== More Medicine (20) =====
  item("FACT", "Blood types are A, B, AB, O, each positive or negative based on Rh factor; O- is the universal donor.", "Antigens on RBCs determine type. A has A antigens, B has B, AB both, O neither. Rh+ has Rh antigen. Transfusion mismatch → immune attack. O- can donate to anyone (no antigens).", "medicine"),
  item("FACT", "Hypertension (high blood pressure) is called the 'silent killer' because it often has no symptoms until damage occurs.", "Defined as >130/80 mmHg. Damages heart, brain, kidneys, eyes, arteries over years. Treat: lifestyle (DASH diet, exercise, low salt, low alcohol) + medication (ACE inhibitors, ARBs, CCBs, diuretics).", "medicine"),
  item("FACT", "A stroke occurs when blood flow to the brain is blocked (ischemic, 87%) or a vessel bursts (hemorrhagic, 13%).", "FAST: Face drooping, Arm weakness, Speech difficulty, Time to call 911. Every minute, 2M brain cells die. Treatment: clot-busting drugs (tPA) within 3-4.5h, mechanical thrombectomy for large clots.", "medicine"),
  item("FACT", "Alzheimer's disease is the most common cause of dementia, characterized by amyloid plaques and tau tangles in the brain.", "Progressive memory loss, confusion, personality changes. Risk: age, genetics (APOE4), lifestyle. No cure yet, but exercise, Mediterranean diet, social/mental activity may delay onset.", "medicine"),
  item("FACT", "Insulin resistance (prediabetes/type 2 diabetes precursor) means cells don't respond well to insulin, requiring more to manage blood sugar.", "Causes: obesity, sedentary, genetics, poor diet. Reversible with weight loss (5-10%), exercise, low-glycemic diet. HbA1c 5.7-6.4% = prediabetes, ≥6.5% = diabetes.", "medicine"),
  item("FACT", "An ECG (electrocardiogram) measures the heart's electrical activity, showing rhythm and detecting heart attacks.", "12-lead ECG standard. P wave (atria contract), QRS (ventricles contract), T wave (ventricles relax). ST elevation = heart attack (STEMI). Arrhythmias, blocks, hypertrophy detectable.", "medicine"),
  item("FACT", "MRI (magnetic resonance imaging) uses strong magnets + radio waves to image soft tissues; CT uses X-rays for bones/dense tissues.", "MRI better for brain, spinal cord, joints, muscles. CT faster, better for trauma, lungs, bones. Neither uses radiation (MRI) vs ionizing (CT). Contrast agents enhance both.", "medicine"),
  item("FACT", "Antibiotic resistance occurs when bacteria evolve to survive antibiotics, often due to overuse/misuse.", "MRSA (methicillin-resistant Staph aureus), MDR-TB (multi-drug-resistant tuberculosis). WHO: 'biggest threat to global health.' Solutions: stewardship, new drugs, vaccines, infection control.", "medicine"),
  item("FACT", "Vaccines work by training the immune system with weakened/dead pathogens or their proteins, creating antibodies + memory cells.", "Types: live-attenuated (MMR, yellow fever), inactivated (polio, rabies), subunit (HPV, hepatitis B), mRNA (COVID-19 Pfizer/Moderna), viral vector (J&J, AstraZeneca).", "medicine"),
  item("FACT", "Type 1 diabetes is autoimmune (pancreas produces no insulin); type 2 is lifestyle-linked (cells resist insulin).", "Type 1: usually childhood, requires lifelong insulin injections. Type 2: 90-95% of cases, often adult-onset (now in kids), managed with diet, exercise, oral meds, sometimes insulin.", "medicine"),
  item("FACT", "The placebo effect is a real improvement in symptoms from a sham treatment, due to patient expectation.", "Can relieve pain, depression, IBS. ~30% of patients respond. Brain releases endorphins, dopamine. Stronger with bigger pills, more invasive procedures, enthusiastic providers. Placebo + real treatment often works better.", "medicine"),
  item("FACT", "Mental health conditions include depression (persistent low mood), anxiety (excessive worry), bipolar (mood swings), schizophrenia (psychosis).", "1 in 4 adults affected yearly. Treatments: therapy (CBT), medication (SSRIs, antipsychotics), lifestyle. Stigma decreasing. Suicidal thoughts → call/text 988 (US).", "medicine"),
  item("FACT", "A concussion is a mild traumatic brain injury from a bump/jolt, causing temporary symptoms (headache, confusion, dizziness).", "Most recover in 1-2 weeks. Rest (physical + cognitive) initially, gradual return to activity. Repeat concussions risk CTE (chronic traumatic encephalopathy). Sports protocols exist.", "medicine"),
  item("FACT", "Skin has 3 layers: epidermis (outer), dermis (middle, with hair/sweat glands), hypodermis (fat, insulation).", "Largest organ (~2 m², ~4 kg). Regenerates every ~28 days. Sweating regulates temperature. Vitamin D synthesis from UV. Melanin protects from UV (sunburn, cancer risk).", "medicine"),
  item("FACT", "The human eye has ~120 million rods (low-light, grayscale) and ~6 million cones (color, bright light).", "Rods concentrated at periphery, cones at center (fovea). Blind spot where optic nerve exits. 20/20 vision = normal acuity. Color blindness from cone defects. Cataracts cloud lens.", "medicine"),
  item("FACT", "Asthma is chronic inflammation of airways causing wheezing, coughing, shortness of breath; triggers include allergens, exercise, cold air.", "Treated with inhalers: relievers (bronchodilators — open airways quickly) + preventers (corticosteroids — reduce inflammation). Severe attacks need ER. Action plans help self-management.", "medicine"),
  item("FACT", "First aid for burns: cool with running water 20 min, remove constrictive items, don't apply ice/butter/cream, cover loosely with cling film or clean cloth.", "First degree: red, painful. Second: blisters. Third: white/charred, painless (nerves dead). Seek help for face, hands, feet, genitals, large area, chemical/electrical. Tetanus risk.", "medicine"),
  item("FACT", "Heimlich maneuver for infants (<1 year): 5 back blows (heel of hand between shoulder blades) + 5 chest thrusts (2 fingers mid-chest).", "Don't do abdominal thrusts on infants. If unconscious, start CPR. For adults: stand behind, fist above navel, thrust inward+upward. Self-Heimlich: thrust abdomen against chair back.", "medicine"),
  item("FACT", "Dehydration symptoms: thirst, dark urine, headache, dizziness, fatigue, dry mouth; severe causes confusion, no urination, rapid heartbeat.", "Adults need ~2-3 L water/day (from drinks + food). Hot weather, exercise, fever, diarrhea increase needs. Sport drinks for heavy sweating (electrolytes). Elderly have reduced thirst.", "medicine"),
  item("FACT", "Food poisoning symptoms (nausea, vomiting, diarrhea, cramps) usually start 6-48h after eating contaminated food, resolving in 1-3 days.", "Common causes: Salmonella (eggs, poultry), E. coli (undercooked beef), Norovirus, Listeria (deli meat, soft cheese). Prevention: cook thoroughly, separate raw/cooked, refrigerate, wash hands.", "medicine"),

  // ===== Languages & Linguistics (15) =====
  item("FACT", "English has borrowed words from over 350 languages, with Latin, French, Greek, and Norse being the largest contributors.", "About 60% of English vocabulary is Latin-based (often via French). Germanic words (be, have, house, man) are more commonly used in daily speech despite being fewer.", "language"),
  item("FACT", "Mandarin Chinese is a tonal language with 4 tones (flat, rising, falling-rising, falling) that change meaning.", "E.g., 'ma' can mean mother, hemp, horse, or scold depending on tone. Written Chinese uses ~50,000 characters; ~3,000 needed for daily literacy. Pinyin romanization uses diacritics for tones.", "language"),
  item("FACT", "Arabic is written right-to-left, has 28 letters, and is the 5th most spoken language with ~420M speakers.", "Numerals we use (0-9) originated in India but came via Arabs. Arabic has dialects (Modern Standard, Egyptian, Gulf, Maghrebi). Quranic Arabic is classical. ~1.9B Muslims study it for prayer.", "language"),
  item("FACT", "Spanish is phonetic — words are pronounced as written — making it relatively easy for English speakers to learn.", "~500M native speakers (2nd after Mandarin). Spoken in 21 countries. Latin American Spanish differs from Castilian (Spain) in pronunciation (th for c/z) and vocabulary (coche/auto, computadora/ordenador).", "language"),
  item("FACT", "French is an official language in 29 countries and was the language of European diplomacy for centuries.", "~300M speakers. Known for nasal sounds, liaison (linking words), and silent letters. French Academy (1635) regulates the language. English borrowed ~30% of vocabulary from French (post-1066 Norman conquest).", "language"),
  item("FACT", "German is famous for compound nouns — long words formed by joining smaller ones (e.g. Schadenfreude, Zeitgeist).", "Compound written as one word. Cases: nominative, accusative, dative, genitive. 3 genders (der, die, das). Longest official word: Rindfleischetikettierungsüberwachungsaufgabenübertragungsgesetz (repealed 2013).", "language"),
  item("FACT", "Korean uses Hangul, a featural alphabet created by King Sejong in 1443, considered one of the most scientific writing systems.", "14 consonants + 10 vowels = 24 letters, arranged in syllable blocks. Consonant shapes mimic mouth/tongue position. Learned in hours (vs years for Chinese characters).", "language"),
  item("FACT", "Japanese uses three writing systems: Kanji (Chinese characters), Hiragana (native syllabary), and Katakana (foreign words).", "Kanji (~2,000+ for literacy) conveys meaning. Hiragana for grammar/inflection. Katakana for loanwords (コンピュータ). Romaji = romanization. Japanese has pitch accent.", "language"),
  item("FACT", "Hindi is written in Devanagari script and is the 3rd most spoken language globally (~600M total speakers).", "Devanagari is abugida (each consonant has inherent 'a' vowel). Sanskrit (ancient) also uses Devanagari. Hindi + Urdu are mutually intelligible spoken (Hindustani) but use different scripts.", "language"),
  item("FACT", "Russian uses Cyrillic alphabet (33 letters), with cases (6) and perfective/imperfective verb aspects.", "~260M speakers. Cyrillic created in 9th century by disciples of Cyril (Byzantine monks). Russian is the most spoken Slavic language. Cases: nominative, accusative, genitive, dative, instrumental, prepositional.", "language"),
  item("FACT", "Latin is a 'dead' language (no native speakers) but heavily influenced English, Spanish, French, Italian, Portuguese, Romanian.", "Vulgar Latin (spoken) evolved into Romance languages. Classical Latin (literary) still used in science, medicine, law, Catholic Church. Latin alphabet used by ~70% of world's population.", "language"),
  item("FACT", "Esperanto is the most successful constructed (artificial) language, created in 1887 by L.L. Zamenhof as a universal second language.", "Designed to be easy (regular grammar, no exceptions). ~2M speakers worldwide, ~1,000 native. Has culture, literature, music. Never achieved wide adoption but community persists.", "language"),
  item("FACT", "Sign languages are full natural languages with their own grammar, not just signed versions of spoken languages.", "ASL (American Sign Language) is distinct from English (different word order, grammar). Different countries have different sign languages (BSL, LSF). Used by Deaf communities worldwide.", "language"),
  item("FACT", "English spelling is notoriously irregular due to historical sound changes and frozen spellings.", "'ough' has ~10 pronunciations: though, through, rough, cough, thought, bough, borough, hiccough. Great Vowel Shift (15th-18th c.) changed pronunciation but not spelling. Spelling bees unique to English.", "language"),
  item("FACT", "An idiom's meaning isn't predictable from its words: 'kick the bucket' (die), 'piece of cake' (easy), 'break a leg' (good luck).", "Idioms reveal cultural thinking. Translating literally fails. Non-native speakers struggle. ~25,000 idioms in English. Other languages have their own: Spanish 'no tengo pelo' (no hair = no problem), German 'Tomaten auf den Augen' (tomatoes on eyes = oblivious).", "language"),
];

export async function seedGeneralKnowledgeV3(tenantId: string, applicationId: string): Promise<{ sourceId: string; itemCount: number }> {
  const { db } = await import("@/lib/db");
  const { buildTermVector, serializeVector } = await import("./vectors");

  let source = await db.knowledgeSource.findFirst({
    where: { tenantId, title: GENERAL_KNOWLEDGE_SOURCE_V3.title },
  });
  if (!source) {
    source = await db.knowledgeSource.create({
      data: {
        tenantId,
        sourceType: GENERAL_KNOWLEDGE_SOURCE_V3.sourceType,
        title: GENERAL_KNOWLEDGE_SOURCE_V3.title,
        author: GENERAL_KNOWLEDGE_SOURCE_V3.author,
        trustLevel: GENERAL_KNOWLEDGE_SOURCE_V3.trustLevel,
        verificationStatus: GENERAL_KNOWLEDGE_SOURCE_V3.verificationStatus,
        dataClassification: GENERAL_KNOWLEDGE_SOURCE_V3.dataClassification,
      },
    });
  }

  let itemCount = 0;
  for (const k of GENERAL_KNOWLEDGE_BASE_V3) {
    const existing = await db.knowledgeItem.findFirst({
      where: { tenantId, sourceId: source.id, claim: k.claim },
    });
    if (existing) continue;
    await db.knowledgeItem.create({
      data: {
        tenantId,
        applicationId,
        sourceId: source.id,
        type: k.type,
        scope: k.scope ?? "APPLICATION",
        claim: k.claim,
        content: k.content,
        contentVector: serializeVector(buildTermVector(k.claim + " " + k.content)),
        status: "ACTIVE",
        confidence: 0.85,
        validFrom: k.validFrom ?? new Date(),
        refreshSchedule: "manual",
        lastRefreshedAt: new Date(),
      },
    });
    itemCount++;
  }
  return { sourceId: source.id, itemCount };
}
